project:
  type: website

lang: es
bibliography: references.bib

website:
  title: "Matemática Abierta"
  description: "Cursos, conceptos, problemas y libros abiertos de matemáticas."
  site-url: "https://lachenmann.github.io/matematica-abierta/"
  search: true
  page-navigation: true
  draft-mode: gone

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: cursos/index.qmd
        text: Cursos
      - href: conceptos/index.qmd
        text: Conceptos
      - href: problemas/index.qmd
        text: Problemas
      - href: libros/index.qmd
        text: Libros
      - href: blog/index.qmd
        text: Blog
      - href: acerca-de.qmd
        text: Proyecto
      - href: licencia.qmd
        text: Licencia
      - href: laboratorio-visual.qmd
        text: Diseño

format:
  html:
    theme:
      dark: [darkly, styles.scss]
      light: [cosmo, styles.scss]
    respect-user-color-scheme: false
    toc: true
    html-math-method: mathjax
