<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gustav A. Tachek">
<meta name="description" content="Capítulo del Tratado moderno de Álgebra dedicado a cuerpos ordenados, inversos, división y comparación de cocientes.">

<title>Tratado moderno de Álgebra — Capítulo 27: Cuerpos ordenados – Matemática Abierta</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/brand/ma-mark-light.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-abd1453828c9afad0dbef8585aed8f51.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-453a16fc1411f73e80395cc636d36c03.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/brand/ma-navbar-light.svg" alt="Matemática Abierta" class="navbar-logo light-content">
    <img src="../../assets/brand/ma-navbar-dark.svg" alt="Matemática Abierta" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teoría" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teoría</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teoría">    
        <li>
    <a class="dropdown-item" href="../../teoria/index.html">
 <span class="dropdown-text">Portada de Teoría</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../conceptos/index.html">
 <span class="dropdown-text">Conceptos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teoria/resultados/index.html">
 <span class="dropdown-text">Resultados y teoremas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teoria/metodos/index.html">
 <span class="dropdown-text">Métodos y técnicas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teoria/mapas/index.html">
 <span class="dropdown-text">Mapas y conexiones</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-problemas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Problemas</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-problemas">    
        <li>
    <a class="dropdown-item" href="../../problemas/index.html">
 <span class="dropdown-text">Todos los problemas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../problemas/por-area/index.html">
 <span class="dropdown-text">Por área</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../problemas/por-tecnica/index.html">
 <span class="dropdown-text">Por técnica</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../problemas/por-dificultad/index.html">
 <span class="dropdown-text">Por dificultad</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../problemas/colecciones/index.html">
 <span class="dropdown-text">Colecciones</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cursos" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cursos</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cursos">    
        <li>
    <a class="dropdown-item" href="../../cursos/index.html">
 <span class="dropdown-text">Portada de Cursos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../cursos/calculo-i/index.html">
 <span class="dropdown-text">Cálculo para matemáticos — Cálculo I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../cursos/rutas/index.html">
 <span class="dropdown-text">Rutas de estudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../cursos/lecciones/index.html">
 <span class="dropdown-text">Lecciones</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-libros" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Libros</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-libros">    
        <li>
    <a class="dropdown-item" href="../../libros/index.html">
 <span class="dropdown-text">Portada de Libros</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../libros/para-matematicos/index.html">
 <span class="dropdown-text">Para matemáticos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../libros/tratados/index.html">
 <span class="dropdown-text">Tratados</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../libros/otros/index.html">
 <span class="dropdown-text">Otros libros y monografías</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../libros/capitulos/index.html">
 <span class="dropdown-text">Capítulos publicados</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-explorar" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Explorar</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-explorar">    
        <li>
    <a class="dropdown-item" href="../../explorar/index.html">
 <span class="dropdown-text">Portada de Explorar</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../explorar/areas/index.html">
 <span class="dropdown-text">Áreas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../explorar/temas/index.html">
 <span class="dropdown-text">Índice temático</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../blog/index.html">
 <span class="dropdown-text">Artículos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../explorar/bibliografia/index.html">
 <span class="dropdown-text">Bibliografía</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../explorar/notacion/index.html">
 <span class="dropdown-text">Notación y convenciones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../explorar/glosario/index.html">
 <span class="dropdown-text">Glosario</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-proyecto" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Proyecto</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-proyecto">    
        <li>
    <a class="dropdown-item" href="../../proyecto/index.html">
 <span class="dropdown-text">Portada del Proyecto</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../acerca-de.html">
 <span class="dropdown-text">Acerca de</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../proyecto/politica-editorial.html">
 <span class="dropdown-text">Política editorial</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../proyecto/procedencia-y-derechos.html">
 <span class="dropdown-text">Procedencia y derechos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../licencia.html">
 <span class="dropdown-text">Licencia</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../proyecto/como-citar.html">
 <span class="dropdown-text">Cómo citar</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../proyecto/estado-y-hoja-de-ruta.html">
 <span class="dropdown-text">Estado y hoja de ruta</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#el-problema-introducir-la-división-sin-perder-el-orden" id="toc-el-problema-introducir-la-división-sin-perder-el-orden" class="nav-link active" data-scroll-target="#el-problema-introducir-la-división-sin-perder-el-orden">27.0. El problema: introducir la división sin perder el orden</a></li>
  <li><a href="#definición-de-cuerpo-ordenado" id="toc-definición-de-cuerpo-ordenado" class="nav-link" data-scroll-target="#definición-de-cuerpo-ordenado">27.1. Definición de cuerpo ordenado</a>
  <ul class="collapse">
  <li><a href="#talg-def-00061" id="toc-talg-def-00061" class="nav-link" data-scroll-target="#talg-def-00061">Definición 27.1.1 — Cuerpo ordenado</a></li>
  </ul></li>
  <li><a href="#qué-no-forma-parte-de-la-definición" id="toc-qué-no-forma-parte-de-la-definición" class="nav-link" data-scroll-target="#qué-no-forma-parte-de-la-definición">27.2. Qué no forma parte de la definición</a></li>
  <li><a href="#el-inverso-de-un-elemento-positivo-conserva-la-positividad" id="toc-el-inverso-de-un-elemento-positivo-conserva-la-positividad" class="nav-link" data-scroll-target="#el-inverso-de-un-elemento-positivo-conserva-la-positividad">27.4. El inverso de un elemento positivo conserva la positividad</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00079" id="toc-talg-pro-00079" class="nav-link" data-scroll-target="#talg-pro-00079">Proposición 27.4.1 — Positividad del inverso de un elemento positivo</a></li>
  </ul></li>
  <li><a href="#el-inverso-de-un-elemento-negativo-es-negativo" id="toc-el-inverso-de-un-elemento-negativo-es-negativo" class="nav-link" data-scroll-target="#el-inverso-de-un-elemento-negativo-es-negativo">27.6. El inverso de un elemento negativo es negativo</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00080" id="toc-talg-pro-00080" class="nav-link" data-scroll-target="#talg-pro-00080">Proposición 27.6.1 — Negatividad del inverso de un elemento negativo</a></li>
  </ul></li>
  <li><a href="#inversión-y-reversión-del-orden-entre-positivos" id="toc-inversión-y-reversión-del-orden-entre-positivos" class="nav-link" data-scroll-target="#inversión-y-reversión-del-orden-entre-positivos">27.8. Inversión y reversión del orden entre positivos</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00081" id="toc-talg-pro-00081" class="nav-link" data-scroll-target="#talg-pro-00081">Proposición 27.8.1 — La inversión revierte el orden entre elementos positivos</a></li>
  </ul></li>
  <li><a href="#la-inversión-revierte-el-orden-también-entre-negativos" id="toc-la-inversión-revierte-el-orden-también-entre-negativos" class="nav-link" data-scroll-target="#la-inversión-revierte-el-orden-también-entre-negativos">27.10. La inversión revierte el orden también entre negativos</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00082" id="toc-talg-pro-00082" class="nav-link" data-scroll-target="#talg-pro-00082">Proposición 27.10.1 — La inversión revierte el orden entre elementos negativos</a></li>
  </ul></li>
  <li><a href="#el-signo-de-un-producto-por-un-inverso" id="toc-el-signo-de-un-producto-por-un-inverso" class="nav-link" data-scroll-target="#el-signo-de-un-producto-por-un-inverso">27.12. El signo de un producto por un inverso</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00083" id="toc-talg-pro-00083" class="nav-link" data-scroll-target="#talg-pro-00083">Proposición 27.12.1 — Regla de signos de productos por inversos</a></li>
  </ul></li>
  <li><a href="#multiplicar-por-un-inverso-fijo-preservar-o-invertir-el-orden" id="toc-multiplicar-por-un-inverso-fijo-preservar-o-invertir-el-orden" class="nav-link" data-scroll-target="#multiplicar-por-un-inverso-fijo-preservar-o-invertir-el-orden">27.14. Multiplicar por un inverso fijo: preservar o invertir el orden</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00084" id="toc-talg-pro-00084" class="nav-link" data-scroll-target="#talg-pro-00084">Proposición 27.14.1 — Compatibilidad del orden estricto con la multiplicación por inversos de signo conocido</a></li>
  </ul></li>
  <li><a href="#orden-no-estricto-al-multiplicar-por-un-inverso-de-signo-conocido" id="toc-orden-no-estricto-al-multiplicar-por-un-inverso-de-signo-conocido" class="nav-link" data-scroll-target="#orden-no-estricto-al-multiplicar-por-un-inverso-de-signo-conocido">27.16. Orden no estricto al multiplicar por un inverso de signo conocido</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00085" id="toc-talg-pro-00085" class="nav-link" data-scroll-target="#talg-pro-00085">Proposición 27.16.1 — Compatibilidad del orden no estricto con la multiplicación por inversos de signo conocido</a></li>
  </ul></li>
  <li><a href="#división-convertir-la-multiplicación-por-un-inverso-en-una-función-de-dominio-explícito" id="toc-división-convertir-la-multiplicación-por-un-inverso-en-una-función-de-dominio-explícito" class="nav-link" data-scroll-target="#división-convertir-la-multiplicación-por-un-inverso-en-una-función-de-dominio-explícito">27.18. División: convertir la multiplicación por un inverso en una función de dominio explícito</a>
  <ul class="collapse">
  <li><a href="#talg-def-00062" id="toc-talg-def-00062" class="nav-link" data-scroll-target="#talg-def-00062">Definición 27.18.1 — División en un cuerpo: dominio de denominadores no nulos y notación</a></li>
  </ul></li>
  <li><a href="#las-identidades-de-división-son-teoremas-sobre-inversos" id="toc-las-identidades-de-división-son-teoremas-sobre-inversos" class="nav-link" data-scroll-target="#las-identidades-de-división-son-teoremas-sobre-inversos">27.20. Las identidades de división son teoremas sobre inversos</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00086" id="toc-talg-pro-00086" class="nav-link" data-scroll-target="#talg-pro-00086">Proposición 27.20.1 — Identidades básicas de la división y criterio de nulidad</a></li>
  </ul></li>
  <li><a href="#los-cocientes-heredan-el-signo-y-el-orden-de-la-multiplicación-por-inversos" id="toc-los-cocientes-heredan-el-signo-y-el-orden-de-la-multiplicación-por-inversos" class="nav-link" data-scroll-target="#los-cocientes-heredan-el-signo-y-el-orden-de-la-multiplicación-por-inversos">27.22. Los cocientes heredan el signo y el orden de la multiplicación por inversos</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00087" id="toc-talg-pro-00087" class="nav-link" data-scroll-target="#talg-pro-00087">Proposición 27.22.1 — Reglas de signos y comparación de cocientes con denominador de signo conocido</a></li>
  </ul></li>
  <li><a href="#suma-y-producto-de-cocientes-justificar-primero-el-denominador" id="toc-suma-y-producto-de-cocientes-justificar-primero-el-denominador" class="nav-link" data-scroll-target="#suma-y-producto-de-cocientes-justificar-primero-el-denominador">27.24. Suma y producto de cocientes: justificar primero el denominador</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00088" id="toc-talg-pro-00088" class="nav-link" data-scroll-target="#talg-pro-00088">Proposición 27.24.1 — Suma y producto de cocientes con denominadores no nulos</a></li>
  </ul></li>
  <li><a href="#opuestos-y-división-sucesiva-condiciones-de-existencia" id="toc-opuestos-y-división-sucesiva-condiciones-de-existencia" class="nav-link" data-scroll-target="#opuestos-y-división-sucesiva-condiciones-de-existencia">27.26. Opuestos y división sucesiva: condiciones de existencia</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00089" id="toc-talg-pro-00089" class="nav-link" data-scroll-target="#talg-pro-00089">Proposición 27.26.1 — Opuestos y cocientes sucesivos con denominadores no nulos</a></li>
  </ul></li>
  <li><a href="#comparar-cocientes-los-productos-cruzados-y-el-signo-del-factor" id="toc-comparar-cocientes-los-productos-cruzados-y-el-signo-del-factor" class="nav-link" data-scroll-target="#comparar-cocientes-los-productos-cruzados-y-el-signo-del-factor">27.28. Comparar cocientes: los productos cruzados y el signo del factor</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00090" id="toc-talg-pro-00090" class="nav-link" data-scroll-target="#talg-pro-00090">Proposición 27.28.1 — Comparación de cocientes por productos cruzados con denominadores de signo conocido</a></li>
  </ul></li>
  <li><a href="#amplificar-y-simplificar-un-cociente-el-factor-común-debe-ser-no-nulo" id="toc-amplificar-y-simplificar-un-cociente-el-factor-común-debe-ser-no-nulo" class="nav-link" data-scroll-target="#amplificar-y-simplificar-un-cociente-el-factor-común-debe-ser-no-nulo">27.30. Amplificar y simplificar un cociente: el factor común debe ser no nulo</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00091" id="toc-talg-pro-00091" class="nav-link" data-scroll-target="#talg-pro-00091">Proposición 27.30.1 — Amplificación y simplificación de cocientes por factores no nulos</a></li>
  </ul></li>
  <li><a href="#normalizar-el-signo-del-denominador" id="toc-normalizar-el-signo-del-denominador" class="nav-link" data-scroll-target="#normalizar-el-signo-del-denominador">27.32. Normalizar el signo del denominador</a>
  <ul class="collapse">
  <li><a href="#talg-pro-00092" id="toc-talg-pro-00092" class="nav-link" data-scroll-target="#talg-pro-00092">Proposición 27.32.1 — Normalización de cocientes a denominador positivo</a></li>
  </ul></li>
  <li><a href="#comparar-después-de-normalizar-un-único-sentido-de-cruce" id="toc-comparar-después-de-normalizar-un-único-sentido-de-cruce" class="nav-link" data-scroll-target="#comparar-después-de-normalizar-un-único-sentido-de-cruce">27.34. Comparar después de normalizar: un único sentido de cruce</a>
  <ul class="collapse">
  <li><a href="#talg-cor-00020" id="toc-talg-cor-00020" class="nav-link" data-scroll-target="#talg-cor-00020">Corolario 27.34.1 — Reducción de comparaciones de cocientes a denominadores positivos</a></li>
  </ul></li>
  <li><a href="#síntesis-deductiva-del-capítulo" id="toc-síntesis-deductiva-del-capítulo" class="nav-link" data-scroll-target="#síntesis-deductiva-del-capítulo">27.36. Síntesis deductiva del capítulo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tratado moderno de Álgebra — Capítulo 27: Cuerpos ordenados</h1>
</div>

<div>
  <div class="description">
    Capítulo del Tratado moderno de Álgebra dedicado a cuerpos ordenados, inversos, división y comparación de cocientes.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Gustav A. Tachek </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Fecha de última modificación</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">2 de octubre de 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="el-problema-introducir-la-división-sin-perder-el-orden" class="level2">
<h2 class="anchored" data-anchor-id="el-problema-introducir-la-división-sin-perder-el-orden">27.0. El problema: introducir la división sin perder el orden</h2>
<p>El capítulo 22 construyó los cuerpos como <strong>anillos conmutativos no triviales</strong> en los que todo elemento no nulo es invertible (Definición 22.1.1). El capítulo 26 construyó independientemente los anillos totalmente ordenados (Definición 26.12.1): el grupo aditivo es totalmente ordenado y el conjunto de elementos no negativos es cerrado bajo multiplicación.</p>
<p>Al reunir ambas condiciones no debemos introducir clandestinamente otra propiedad. En particular, la positividad de la unidad, la inexistencia de divisores de cero y las reglas estrictas del producto serán <strong>consecuencias de resultados anteriores</strong>, no axiomas adicionales de la nueva definición.</p>
<pre class="text"><code>    cuerpo                            anillo totalmente ordenado
    (Def. 22.1.1)                    (Def. 26.12.1)
    conmutativo                       grupo aditivo totalmente ordenado
    no trivial                        producto de no negativos ≥ 0
    inversos para a ≠ 0                      │
         └─────────────────────────┬────────┘
                                   ▼
                            CUERPO ORDENADO</code></pre>
<p><strong>Pregunta de activación.</strong> ¿Qué distingue al nuevo objeto de un anillo totalmente ordenado? Que todo elemento no nulo dispone ahora de inverso multiplicativo; además, la definición previa de cuerpo ya proporciona conmutatividad y <span class="math inline">\(0\ne1\)</span>.</p>
<hr>
</section>
<section id="definición-de-cuerpo-ordenado" class="level2">
<h2 class="anchored" data-anchor-id="definición-de-cuerpo-ordenado">27.1. Definición de cuerpo ordenado</h2>
<section id="talg-def-00061" class="level3">
<h3 class="anchored" data-anchor-id="talg-def-00061">Definición 27.1.1 — Cuerpo ordenado</h3>
<p>Sea <span class="math inline">\(F\)</span> un conjunto con operaciones binarias <span class="math inline">\(+\)</span>, <span class="math inline">\(\cdot\)</span> y una relación <span class="math inline">\(\le\)</span> sobre <span class="math inline">\(F\)</span>. Diremos que</p>
<p><span class="math display">\[
\langle F,+,\cdot,\le\rangle
\]</span></p>
<p>es un <strong>cuerpo ordenado</strong> si se satisfacen simultáneamente las siguientes condiciones:</p>
<ol type="1">
<li><span class="math inline">\(\langle F,+,\cdot\rangle\)</span> es un <strong>cuerpo</strong> en el sentido de la Definición 22.1.1.</li>
<li><span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> es un <strong>anillo totalmente ordenado</strong> en el sentido de la Definición 26.12.1.</li>
</ol>
<p>La segunda condición significa, explícitamente, que <span class="math inline">\(\le\)</span> es un orden total compatible con las traslaciones aditivas y que</p>
<p><span class="math display">\[
\forall a,b\in F,\qquad
(0\le a\ \land\ 0\le b)\Longrightarrow 0\le ab.
\]</span></p>
<p>La primera incorpora conmutatividad, <span class="math inline">\(0\ne1\)</span> y la existencia de inversos multiplicativos para todos los elementos no nulos. Por ello la estructura no es un «anillo de división ordenado» no conmutativo ni admite el anillo trivial.</p>
<blockquote class="blockquote">
<p><strong>Consecuencia ya demostrada, no axioma nuevo.</strong> La Proposición 26.16.1 prueba que la unidad de cualquier anillo totalmente ordenado es no negativa y, si el anillo es no trivial, estrictamente positiva. Como un cuerpo cumple <span class="math inline">\(0\ne1\)</span>, en todo cuerpo ordenado tenemos <span class="math inline">\(0&lt;1\)</span>. No constituye una condición tercera de la definición.</p>
</blockquote>
<p>La notación de cuádrupla es una abreviatura tipográfica de la codificación conjuntista convencional. La definición no presupone que la comparación o la igualdad sean decidibles, ni proporciona un algoritmo para calcular inversos. La existencia de inversos se toma de la definición de cuerpo, sin apelar a Choice.</p>
<hr>
</section>
</section>
<section id="qué-no-forma-parte-de-la-definición" class="level2">
<h2 class="anchored" data-anchor-id="qué-no-forma-parte-de-la-definición">27.2. Qué no forma parte de la definición</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>enunciado</th>
<th>estatus lógico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0&lt;1\)</span></td>
<td>consecuencia previa: cuerpo no trivial + Proposición 26.16.1</td>
</tr>
<tr class="even">
<td>todo <span class="math inline">\(a\ne0\)</span> posee inverso multiplicativo</td>
<td>contenido de la definición previa de cuerpo</td>
</tr>
<tr class="odd">
<td>no existen divisores de cero</td>
<td>teorema previo para cuerpos, no axioma adicional</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0&lt;a\Longrightarrow 0&lt;a^{-1}\)</span></td>
<td>Proposición 27.4.1, demostrada en esta unidad</td>
</tr>
<tr class="odd">
<td>la comparación <span class="math inline">\(a\le b\)</span> es algorítmicamente decidible</td>
<td>no se afirma</td>
</tr>
<tr class="even">
<td>existen supremos de subconjuntos acotados</td>
<td>no se afirma</td>
</tr>
<tr class="odd">
<td>el cuerpo es arquimediano</td>
<td>no se afirma</td>
</tr>
</tbody>
</table>
<p>Los ejemplos enteros y racionales de este capítulo usan las estructuras y las incrustaciones importadas en la Interfaz 24.0.1.</p>
<p><strong>No-ejemplo conceptual.</strong> Un anillo totalmente ordenado con elementos no nulos que carecen de inverso no es automáticamente un cuerpo ordenado. Así, el orden usual de <span class="math inline">\(\mathbb Z\)</span> es compatible con suma y multiplicación y es total, pero <span class="math inline">\(2\)</span> no tiene inverso multiplicativo en <span class="math inline">\(\mathbb Z\)</span>. En efecto, la forma normal entera y el orden natural dan, para todo entero <span class="math inline">\(z\)</span>, <span class="math inline">\(z\le0\)</span> o <span class="math inline">\(1\le z\)</span>. En el primer caso <span class="math inline">\(2z\le0&lt;1\)</span>; en el segundo <span class="math inline">\(2z\ge2&gt;1\)</span>. Por tanto <span class="math inline">\(2z=1\)</span> es imposible. Esta observación ilustra la necesidad de la primera condición; no interviene en ninguna demostración.</p>
<p><strong>Lectura inversa.</strong> Para comprobar si una estructura dada es un cuerpo ordenado hay que verificar primero las propiedades de cuerpo y, separadamente, la compatibilidad ordenada. No basta con demostrar <span class="math inline">\(0&lt;1\)</span> ni con disponer de un orden total cualquiera: el cono no negativo debe ser multiplicativamente estable.</p>
<hr>
</section>
<section id="el-inverso-de-un-elemento-positivo-conserva-la-positividad" class="level2">
<h2 class="anchored" data-anchor-id="el-inverso-de-un-elemento-positivo-conserva-la-positividad">27.4. El inverso de un elemento positivo conserva la positividad</h2>
<p>La división introduce una dificultad que no surgía para la multiplicación: sabemos que un elemento positivo y no nulo posee un inverso, pero todavía no conocemos su signo. Por tanto, <strong>no está permitido multiplicar una desigualdad por <span class="math inline">\(a^{-1}\)</span> como si su positividad ya estuviera probada</strong>. La estrategia correcta es multiplicar por el elemento <span class="math inline">\(a\)</span>, cuyo signo sí está controlado, y utilizar la totalidad para identificar el signo del inverso.</p>
<pre class="text"><code>0 &lt; a  ⇒  a ≠ 0  ⇒  existe a⁻¹ y a·a⁻¹ = 1
                              │
                    ¿a⁻¹ ≤ 0? ── multiplicar por a ≥ 0
                              │
                              ▼
                          1 ≤ 0  ✗  (porque 0 &lt; 1)
                              │
             totalidad: 0 ≤ a⁻¹  o  a⁻¹ ≤ 0
                              │
                  sólo queda 0 ≤ a⁻¹
                              │
                  a⁻¹ ≠ 0  ⇒  0 &lt; a⁻¹</code></pre>
<section id="talg-pro-00079" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00079">Proposición 27.4.1 — Positividad del inverso de un elemento positivo</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para todo <span class="math inline">\(a\in F\)</span>,</p>
<p><span class="math display">\[
0&lt;a\ \Longrightarrow\ 0&lt;a^{-1}.
\]</span></p>
<p>El inverso del consecuente existe porque <span class="math inline">\(0&lt;a\)</span> implica <span class="math inline">\(a\ne0\)</span>, y la definición de cuerpo garantiza que todo elemento no nulo es invertible.</p>
<section id="talg-prf-00123" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00123">Demostración</h4>
<p>Supongamos <span class="math inline">\(0&lt;a\)</span>. Por la definición de orden estricto asociado (interfaz de órdenes, Interfaz 25.1.1), tenemos simultáneamente</p>
<p><span class="math display">\[
0\le a,\qquad a\ne0.
\]</span></p>
<p>La definición de cuerpo garantiza un inverso multiplicativo, escrito <span class="math inline">\(a^{-1}\)</span> según la Notación 15.3.1, que satisface</p>
<p><span class="math display">\[
a\cdot a^{-1}=1.
\]</span></p>
<p>Además, la Proposición 26.16.1 da <span class="math inline">\(0&lt;1\)</span>, pues el cuerpo es un anillo totalmente ordenado y no trivial. En particular,</p>
<p><span class="math display">\[
0\le1,\qquad 0\ne1.
\]</span></p>
<p><strong>Primer paso: excluir que el inverso sea no positivo.</strong> Supongamos que <span class="math inline">\(a^{-1}\le0\)</span>. Como <span class="math inline">\(0\le a\)</span>, la monotonía multiplicativa por factores no negativos (Proposición 26.6.1), aplicada <strong>por la izquierda</strong> con factor <span class="math inline">\(a\)</span>, produce</p>
<p><span class="math display">\[
a\cdot a^{-1}\le a\cdot0.
\]</span></p>
<p>La identidad del inverso y la absorción del cero (Proposición 14.3.1) convierten esto en</p>
<p><span class="math display">\[
1\le0.
\]</span></p>
<p>Pero <span class="math inline">\(0\le1\)</span> y la antisimetría del orden implicarían <span class="math inline">\(0=1\)</span>, en contradicción con <span class="math inline">\(0\ne1\)</span>. Por consiguiente,</p>
<p><span class="math display">\[
\neg(a^{-1}\le0).
\]</span></p>
<p><strong>Segundo paso: usar la totalidad, sin postular decidibilidad.</strong> Como el orden del cuerpo es total, aplicado a <span class="math inline">\(0\)</span> y <span class="math inline">\(a^{-1}\)</span> da la disyunción</p>
<p><span class="math display">\[
0\le a^{-1}\quad\lor\quad a^{-1}\le0.
\]</span></p>
<p>La segunda alternativa contradice lo ya probado; por eliminación de la disyunción se obtiene</p>
<p><span class="math display">\[
0\le a^{-1}.
\]</span></p>
<p><strong>Tercer paso: descartar el cero.</strong> Si <span class="math inline">\(a^{-1}=0\)</span>, entonces</p>
<p><span class="math display">\[
1=a\cdot a^{-1}=a\cdot0=0,
\]</span></p>
<p>otra contradicción con la no trivialidad. Así, <span class="math inline">\(a^{-1}\ne0\)</span>. La definición de orden estricto asociado, aplicada a <span class="math inline">\(0\le a^{-1}\)</span> y <span class="math inline">\(a^{-1}\ne0\)</span>, concluye</p>
<p><span class="math display">\[
0&lt;a^{-1}.
\]</span></p>
<p>Queda demostrada la proposición. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada de la prueba.</strong> La desigualdad que se multiplica es <span class="math inline">\(a^{-1}\le0\)</span>, una hipótesis provisional. El factor elegido es <span class="math inline">\(a\ge0\)</span>, cuyo signo está demostrado desde el comienzo. Multiplicar por el inverso en este momento sería circular, pues precisamente se busca averiguar si dicho inverso es positivo.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo intuitivo, no premisa.</strong> En el cuerpo de los racionales con su orden usual, <span class="math inline">\(2&gt;0\)</span> y <span class="math inline">\(2^{-1}=1/2&gt;0\)</span>. El argumento anterior prueba la misma conclusión en <em>todo</em> cuerpo ordenado sin apelar a una representación numérica de sus elementos.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera.</strong> <span class="math inline">\(a=0\)</span> queda excluido por el antecedente estricto; el cero no posee inverso en un cuerpo no trivial. El caso <span class="math inline">\(a&lt;0\)</span> no se infiere de esta proposición por sustitución informal: su tratamiento será un resultado separado.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="el-inverso-de-un-elemento-negativo-es-negativo" class="level2">
<h2 class="anchored" data-anchor-id="el-inverso-de-un-elemento-negativo-es-negativo">27.6. El inverso de un elemento negativo es negativo</h2>
<p>El caso negativo no se obtiene multiplicando una desigualdad por <span class="math inline">\(a^{-1}\)</span> antes de conocer su signo. La idea consiste en transformar primero el dato <span class="math inline">\(a&lt;0\)</span> en una positividad ya tratada: <span class="math inline">\(0&lt;-a\)</span>. Falta justificar una identidad algebraica que no debe darse por supuesta, la relación entre el inverso multiplicativo del opuesto y el opuesto del inverso.</p>
<pre class="text"><code>     a &lt; 0
       │  inversión del orden por opuesto aditivo (25.5.1)
       ▼
     0 &lt; -a
       │  positividad del inverso (27.4.1)
       ▼
     0 &lt; (-a)⁻¹
       │  reglas de signos + unicidad del inverso multiplicativo
       ▼
     0 &lt; -(a⁻¹)
       │  inversión del orden por opuesto aditivo (25.5.1)
       ▼
     a⁻¹ &lt; 0</code></pre>
<section id="talg-pro-00080" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00080">Proposición 27.6.1 — Negatividad del inverso de un elemento negativo</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para todo <span class="math inline">\(a\in F\)</span>,</p>
<p><span class="math display">\[
a&lt;0\quad\Longrightarrow\quad a^{-1}&lt;0.
\]</span></p>
<p>El antecedente implica <span class="math inline">\(a\ne0\)</span> y, por la definición de cuerpo, asegura la existencia del inverso multiplicativo del consecuente.</p>
<section id="talg-prf-00124" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00124">Demostración</h4>
<p>Supongamos <span class="math inline">\(a&lt;0\)</span>. Por la definición del orden estricto asociado, <span class="math inline">\(a\ne0\)</span>. La estructura de cuerpo garantiza un inverso bilateral <span class="math inline">\(a^{-1}\)</span>, determinado de manera única y denotado según la Notación 15.3.1:</p>
<p><span class="math display">\[
a\cdot a^{-1}=a^{-1}\cdot a=1.
\]</span></p>
<p><strong>Primer paso: convertir el antecedente en una desigualdad positiva.</strong> La inversión del orden estricto por el opuesto aditivo (Proposición 25.5.1), aplicada a <span class="math inline">\(a&lt;0\)</span>, da <span class="math inline">\(-0&lt;-a\)</span>. Como el opuesto aditivo del cero es el propio cero,</p>
<p><span class="math display">\[
0&lt;-a.
\]</span></p>
<p>En particular, <span class="math inline">\(-a\ne0\)</span> y existe su inverso multiplicativo <span class="math inline">\((-a)^{-1}\)</span>. La Proposición 27.4.1, aplicada <strong>a <span class="math inline">\(-a\)</span></strong>, cuyo signo ya está demostrado, implica</p>
<p><span class="math display">\[
0&lt;(-a)^{-1}.
\]</span></p>
<p><strong>Segundo paso: justificar la identidad algebraica de inversos.</strong> El elemento <span class="math inline">\(-(a^{-1})\)</span> es candidato a inverso bilateral de <span class="math inline">\(-a\)</span>. Las reglas de signos de la Proposición 14.4.1 prueban, sin emplear desigualdades,</p>
<p><span class="math display">\[
(-a)\cdot\bigl(-(a^{-1})\bigr)
=a\cdot a^{-1}=1,
\]</span></p>
<p>y, conservando explícitamente la otra lateralidad,</p>
<p><span class="math display">\[
\bigl(-(a^{-1})\bigr)\cdot(-a)
=a^{-1}\cdot a=1.
\]</span></p>
<p>La unicidad del inverso multiplicativo (Proposición 15.2.1) permite identificar ambos elementos:</p>
<p><span class="math display">\[
(-a)^{-1}=-(a^{-1}).
\]</span></p>
<p>No se trata de una convención de signos, sino de una igualdad demostrada. Sustituyéndola en la desigualdad del primer paso obtenemos</p>
<p><span class="math display">\[
0&lt;-(a^{-1}).
\]</span></p>
<p><strong>Tercer paso: recuperar el signo buscado.</strong> Aplicamos de nuevo la inversión del orden estricto por el opuesto aditivo (Proposición 25.5.1):</p>
<p><span class="math display">\[
-\bigl(-(a^{-1})\bigr)&lt;-0.
\]</span></p>
<p>Por la involución del opuesto y la identidad <span class="math inline">\(-0=0\)</span>,</p>
<p><span class="math display">\[
a^{-1}&lt;0.
\]</span></p>
<p>Queda demostrada la proposición. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> El primer inverso cuyo signo se estudia es el de <span class="math inline">\(-a\)</span>, elemento positivo. La igualdad <span class="math inline">\((-a)^{-1}=-(a^{-1})\)</span> se comprueba con los dos productos y la unicidad del inverso. Sólo entonces se traslada el signo a <span class="math inline">\(a^{-1}\)</span>; en ningún momento se multiplicó por un factor de signo desconocido.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo ilustrativo, no premisa.</strong> Con el orden usual de los racionales, <span class="math inline">\(-2&lt;0\)</span> y <span class="math inline">\((-2)^{-1}=-1/2&lt;0\)</span>. El razonamiento anterior no depende de esta representación y se aplica a cualquier cuerpo ordenado.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera.</strong> No puede sustituirse <span class="math inline">\(a&lt;0\)</span> por <span class="math inline">\(a\le0\)</span>: <span class="math inline">\(a=0\)</span> satisface la desigualdad débil, pero carece de inverso multiplicativo en un cuerpo no trivial.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="inversión-y-reversión-del-orden-entre-positivos" class="level2">
<h2 class="anchored" data-anchor-id="inversión-y-reversión-del-orden-entre-positivos">27.8. Inversión y reversión del orden entre positivos</h2>
<p>Ya sabemos que el inverso de un positivo es positivo (Proposición 27.4.1). Eso <strong>no prueba todavía</strong> cómo se comparan dos inversos. La estrategia preserva inicialmente una desigualdad no estricta multiplicándola por factores cuyo signo ya está demostrado; la estricta se recupera mediante la inyectividad de la inversión, justificada algebraicamente, y no mediante un supuesto tácito de cancelación.</p>
<pre class="text"><code>         0 &lt; a &lt; b
           │  positividad de los inversos (27.4.1)
           ▼
       0 &lt; a⁻¹, b⁻¹
           │  a ≤ b; multiplicar a la derecha por b⁻¹ ≥ 0
           ▼
         ab⁻¹ ≤ 1
           │  multiplicar a la izquierda por a⁻¹ ≥ 0
           ▼
         b⁻¹ ≤ a⁻¹
           │  igualdad de inversos ⇒ a=b; contradice a&lt;b
           ▼
         b⁻¹ &lt; a⁻¹</code></pre>
<section id="talg-pro-00081" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00081">Proposición 27.8.1 — La inversión revierte el orden entre elementos positivos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para cualesquiera <span class="math inline">\(a,b\in F\)</span> tales que <span class="math inline">\(0&lt;a\)</span> y <span class="math inline">\(0&lt;b\)</span>,</p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad b^{-1}&lt;a^{-1}.
\]</span></p>
<p>En particular, la inversión es <strong>estrictamente antítona</strong> en el conjunto de elementos positivos. Las hipótesis <span class="math inline">\(0&lt;a\)</span> y <span class="math inline">\(0&lt;b\)</span> garantizan la existencia de ambos inversos y el conocimiento previo de sus signos.</p>
<section id="talg-prf-00125" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00125">Demostración</h4>
<p>Por <span class="math inline">\(0&lt;a\)</span> y <span class="math inline">\(0&lt;b\)</span>, la definición de cuerpo y la Notación 15.3.1 proporcionan inversos bilaterales, con</p>
<p><span class="math display">\[
a^{-1}a=aa^{-1}=1,\qquad b^{-1}b=bb^{-1}=1.
\]</span></p>
<p>La Proposición 27.4.1, aplicada <strong>por separado a <span class="math inline">\(a\)</span> y a <span class="math inline">\(b\)</span></strong>, establece</p>
<p><span class="math display">\[
0&lt;a^{-1},\qquad 0&lt;b^{-1}.
\]</span></p>
<p>Por la definición del orden estricto asociado, ambos inversos son también no negativos.</p>
<p><strong>Primera implicación.</strong> Supongamos <span class="math inline">\(a&lt;b\)</span>. Por definición, <span class="math inline">\(a\le b\)</span> y <span class="math inline">\(a\ne b\)</span>. Multiplicamos <span class="math inline">\(a\le b\)</span> <strong>por la derecha</strong> por <span class="math inline">\(b^{-1}\ge0\)</span>; la Proposición 26.6.1 da</p>
<p><span class="math display">\[
ab^{-1}\le bb^{-1}=1.
\]</span></p>
<p>Multiplicamos ahora esta desigualdad <strong>por la izquierda</strong> por <span class="math inline">\(a^{-1}\ge0\)</span>, usando nuevamente la Proposición 26.6.1. Por asociatividad e identidad multiplicativa,</p>
<p><span class="math display">\[
a^{-1}(ab^{-1})\le a^{-1}1,
\qquad\text{es decir,}\qquad b^{-1}\le a^{-1}.
\]</span></p>
<p>Justifiquemos que la desigualdad es estricta. Si <span class="math inline">\(b^{-1}=a^{-1}\)</span>, podemos multiplicar <strong>la igualdad</strong> por <span class="math inline">\(a\)</span> a la izquierda y por <span class="math inline">\(b\)</span> a la derecha; las identidades de inversos dan</p>
<p><span class="math display">\[
a(b^{-1}b)=(aa^{-1})b
\quad\Longrightarrow\quad a=b,
\]</span></p>
<p>contrariamente a <span class="math inline">\(a\ne b\)</span>. Luego <span class="math inline">\(b^{-1}\ne a^{-1}\)</span>, y la definición de orden estricto concluye</p>
<p><span class="math display">\[
b^{-1}&lt;a^{-1}.
\]</span></p>
<p><strong>Segunda implicación.</strong> Supongamos <span class="math inline">\(b^{-1}&lt;a^{-1}\)</span>. Ya hemos probado que <span class="math inline">\(b^{-1}\)</span> y <span class="math inline">\(a^{-1}\)</span> son positivos. Podemos aplicarles la <strong>primera implicación ya demostrada</strong>, tomando <span class="math inline">\(u=b^{-1}\)</span> y <span class="math inline">\(v=a^{-1}\)</span>; resulta</p>
<p><span class="math display">\[
(a^{-1})^{-1}&lt;(b^{-1})^{-1}.
\]</span></p>
<p>Para identificar estos inversos iterados no postulamos una nueva ley: <span class="math inline">\(a\)</span> es inverso bilateral de <span class="math inline">\(a^{-1}\)</span> porque <span class="math inline">\(aa^{-1}=a^{-1}a=1\)</span>. La unicidad del inverso multiplicativo (Proposición 15.2.1) asegura <span class="math inline">\((a^{-1})^{-1}=a\)</span>. Análogamente, <span class="math inline">\((b^{-1})^{-1}=b\)</span>. Por sustitución,</p>
<p><span class="math display">\[
a&lt;b.
\]</span></p>
<p>Quedan probadas las dos implicaciones. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> No se multiplica por un inverso hasta conocer su positividad, probada en §27.4. La monotonía no estricta proporciona primero <span class="math inline">\(b^{-1}\le a^{-1}\)</span>; el paso a <span class="math inline">\(&lt;\)</span> necesita descartar la igualdad mediante identidades multiplicativas. La vuelta de la equivalencia sólo reutiliza la implicación directa ya cerrada y la unicidad de inversos, sin razonamiento circular.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo no deductivo.</strong> En <span class="math inline">\(\mathbb Q\)</span> con el orden usual, <span class="math inline">\(0&lt;2&lt;5\)</span> y <span class="math inline">\(0&lt;1/5&lt;1/2\)</span>: el menor positivo tiene inverso mayor. El ejemplo ilustra, pero no fundamenta, la proposición.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Límite del dominio.</strong> La inversión no revierte el orden en todo <span class="math inline">\(F\setminus\{0\}\)</span> sin distinguir signos: <span class="math inline">\(-1&lt;1\)</span>, pero <span class="math inline">\(1^{-1}=1\)</span> no es menor que <span class="math inline">\((-1)^{-1}=-1\)</span>. El caso de dos números negativos exige una prueba independiente, reservada para §27.10. Si <span class="math inline">\(a=0\)</span> o <span class="math inline">\(b=0\)</span>, alguna expresión inversa carece de sentido.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="la-inversión-revierte-el-orden-también-entre-negativos" class="level2">
<h2 class="anchored" data-anchor-id="la-inversión-revierte-el-orden-también-entre-negativos">27.10. La inversión revierte el orden también entre negativos</h2>
<p>La reversión del orden entre positivos (Proposición 27.8.1) no puede aplicarse <em>directamente</em> a números negativos. Pero la inversión del orden estricto al tomar opuestos convierte ambos negativos en positivos. Hay que conservar cuidadosamente el orden de los términos: si <span class="math inline">\(a&lt;b&lt;0\)</span>, entonces <span class="math inline">\(0&lt;-b&lt;-a\)</span>, no <span class="math inline">\(0&lt;-a&lt;-b\)</span>. El vínculo entre ambos inversos ya fue establecido en la demostración de la Proposición 27.6.1.</p>
<pre class="text"><code>            a &lt; b &lt; 0
               │ tomar opuestos; invertir el orden (25.5.1)
               ▼
           0 &lt; -b &lt; -a
               │ aplicar 27.8.1 a los positivos -b y -a
               ▼
        (-a)⁻¹ &lt; (-b)⁻¹
               │ identidad de inversos de opuestos (§27.6)
               ▼
          -a⁻¹ &lt; -b⁻¹
               │ tomar opuestos; invertir el orden
               ▼
            b⁻¹ &lt; a⁻¹</code></pre>
<section id="talg-pro-00082" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00082">Proposición 27.10.1 — La inversión revierte el orden entre elementos negativos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para cualesquiera <span class="math inline">\(a,b\in F\)</span> tales que <span class="math inline">\(a&lt;0\)</span> y <span class="math inline">\(b&lt;0\)</span>,</p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad b^{-1}&lt;a^{-1}.
\]</span></p>
<p>Además, ambos inversos son negativos:</p>
<p><span class="math display">\[
a^{-1}&lt;0,\qquad b^{-1}&lt;0.
\]</span></p>
<p>Las hipótesis excluyen el cero y garantizan que los inversos existen. El enunciado es una comparación <strong>dentro de la región negativa</strong>, no entre factores de signos opuestos.</p>
<section id="talg-prf-00126" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00126">Demostración</h4>
<p>Sean <span class="math inline">\(a,b&lt;0\)</span>. Por la Definición 27.1.1 y la Notación 15.3.1 existen sus inversos bilaterales <span class="math inline">\(a^{-1}\)</span> y <span class="math inline">\(b^{-1}\)</span>. La Proposición 27.6.1 prueba que</p>
<p><span class="math display">\[
a^{-1}&lt;0,\qquad b^{-1}&lt;0.
\]</span></p>
<p><strong>Paso preparatorio: establecer los opuestos y la identidad algebraica pertinente.</strong> De <span class="math inline">\(a&lt;0\)</span> y <span class="math inline">\(b&lt;0\)</span>, la Proposición 25.5.1 (inversión del orden estricto por el opuesto aditivo) da</p>
<p><span class="math display">\[
0&lt;-a,\qquad 0&lt;-b.
\]</span></p>
<p>Por tanto también existen <span class="math inline">\((-a)^{-1}\)</span> y <span class="math inline">\((-b)^{-1}\)</span>. La demostración de la Proposición 27.6.1 justificó, multiplicando los candidatos en <strong>ambos órdenes</strong> y usando la unicidad de inversos, que</p>
<p><span class="math display">\[
(-a)^{-1}=-(a^{-1}),\qquad (-b)^{-1}=-(b^{-1}). \tag{1}
\]</span></p>
<p>Esta igualdad es un resultado algebraico previo; no se introduce por una manipulación informal de exponentes.</p>
<p><strong>Primera implicación.</strong> Supongamos <span class="math inline">\(a&lt;b\)</span>. La inversión del orden por el opuesto aditivo da</p>
<p><span class="math display">\[
-b&lt;-a.
\]</span></p>
<p>Ambos miembros son positivos, de manera que la equivalencia ya demostrada en la Proposición 27.8.1, aplicada a <span class="math inline">\(u=-b\)</span> y <span class="math inline">\(v=-a\)</span>, produce</p>
<p><span class="math display">\[
(-a)^{-1}&lt;(-b)^{-1}.
\]</span></p>
<p>Sustituyendo las dos identidades de (1), tenemos</p>
<p><span class="math display">\[
-(a^{-1})&lt;-(b^{-1}).
\]</span></p>
<p>Una segunda aplicación de la Proposición 25.5.1, seguida de la involución del opuesto aditivo, invierte el orden:</p>
<p><span class="math display">\[
b^{-1}&lt;a^{-1}.
\]</span></p>
<p><strong>Segunda implicación.</strong> Supongamos ahora <span class="math inline">\(b^{-1}&lt;a^{-1}\)</span>. Al tomar opuestos, por la misma Proposición 25.5.1,</p>
<p><span class="math display">\[
-(a^{-1})&lt;-(b^{-1}).
\]</span></p>
<p>Mediante las identidades (1), esto equivale a</p>
<p><span class="math display">\[
(-a)^{-1}&lt;(-b)^{-1}.
\]</span></p>
<p>Los elementos <span class="math inline">\(-b\)</span> y <span class="math inline">\(-a\)</span> son positivos. Aplicamos <strong>la implicación inversa de la Proposición 27.8.1</strong> a <span class="math inline">\(u=-b\)</span> y <span class="math inline">\(v=-a\)</span>; resulta</p>
<p><span class="math display">\[
-b&lt;-a.
\]</span></p>
<p>Tomando opuestos una vez más y usando la involución aditiva obtenemos <span class="math inline">\(a&lt;b\)</span>. Quedan demostradas la equivalencia y, por el primer párrafo, la negatividad de ambos inversos. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> La prueba no multiplica desigualdades por números negativos ni considera conocido el signo de un inverso antes de establecerlo. Traslada la comparación al semieje positivo, donde hay una equivalencia previa, y vuelve a través de la identidad algebraica de (1). Las dos implicaciones son distintas y están escritas explícitamente.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo racional, no premisa.</strong> En <span class="math inline">\(\mathbb Q\)</span>, <span class="math inline">\(-5&lt;-2&lt;0\)</span> y <span class="math inline">\(-1/2&lt;-1/5&lt;0\)</span>. Se invierte el orden en el semieje negativo: el inverso de <span class="math inline">\(-2\)</span> es menor que el inverso de <span class="math inline">\(-5\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera y contraejemplo.</strong> El cero carece de inverso en un cuerpo no trivial. Si se cruza el cero, <span class="math inline">\(-1&lt;1\)</span>, pero <span class="math inline">\(1^{-1}=1\)</span> <strong>no</strong> es menor que <span class="math inline">\((-1)^{-1}=-1\)</span>; por tanto, la inversión no es antítona en todo <span class="math inline">\(F\setminus\{0\}\)</span>. Las hipótesis de signo común no deben omitirse.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="el-signo-de-un-producto-por-un-inverso" class="level2">
<h2 class="anchored" data-anchor-id="el-signo-de-un-producto-por-un-inverso">27.12. El signo de un producto por un inverso</h2>
<p>La notación <span class="math inline">\(ab^{-1}\)</span> expresa la multiplicación en el cuerpo por <strong>el inverso multiplicativo de <span class="math inline">\(b\)</span></strong>; todavía no es necesario definir una operación nueva de división ni emplear una barra de fracción. La condición <span class="math inline">\(b\ne0\)</span> asegura que ese inverso exista. Los dos resultados de signos de §27.4 y §27.6 permiten identificar su signo antes de aplicar las reglas multiplicativas del capítulo 26.</p>
<pre class="text"><code> b ≠ 0  ──► existe b⁻¹;  b·b⁻¹ = b⁻¹·b = 1
   │
   ├── b &gt; 0 ──► b⁻¹ &gt; 0  (§27.4)
   └── b &lt; 0 ──► b⁻¹ &lt; 0  (§27.6)

 a·b⁻¹ = 0 ──► (a·b⁻¹)·b = 0·b ──► a = 0
                                │
       a ≠ 0 ──► a·b⁻¹ ≠ 0 ─────┘

 signo(a), signo(b⁻¹) ──► signo(a·b⁻¹)</code></pre>
<section id="talg-pro-00083" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00083">Proposición 27.12.1 — Regla de signos de productos por inversos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para cualesquiera <span class="math inline">\(a,b\in F\)</span> con <span class="math inline">\(b\ne0\)</span>, sea <span class="math inline">\(p=a\cdot b^{-1}\)</span>. Entonces:</p>
<p><strong>I. Criterio exacto de nulidad:</strong></p>
<p><span class="math display">\[
p=0\quad\Longleftrightarrow\quad a=0.
\]</span></p>
<p><strong>II. Reglas de signos estrictos:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>signo de <span class="math inline">\(a\)</span></th>
<th>signo de <span class="math inline">\(b\)</span></th>
<th>signo de <span class="math inline">\(a\cdot b^{-1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0&lt;a\)</span></td>
<td><span class="math inline">\(0&lt;b\)</span></td>
<td><span class="math inline">\(0&lt;p\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a&lt;0\)</span></td>
<td><span class="math inline">\(b&lt;0\)</span></td>
<td><span class="math inline">\(0&lt;p\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0&lt;a\)</span></td>
<td><span class="math inline">\(b&lt;0\)</span></td>
<td><span class="math inline">\(p&lt;0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a&lt;0\)</span></td>
<td><span class="math inline">\(0&lt;b\)</span></td>
<td><span class="math inline">\(p&lt;0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(a=0\)</span></td>
<td><span class="math inline">\(b\ne0\)</span></td>
<td><span class="math inline">\(p=0\)</span></td>
</tr>
</tbody>
</table>
<p>La misma tabla vale para <span class="math inline">\(b^{-1}a\)</span>, puesto que el cuerpo es conmutativo y <span class="math inline">\(a b^{-1}=b^{-1}a\)</span>. La hipótesis <span class="math inline">\(b\ne0\)</span> es indispensable: no se asigna ningún valor a <span class="math inline">\(b^{-1}\)</span> cuando <span class="math inline">\(b=0\)</span>.</p>
<section id="talg-prf-00127" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00127">Demostración</h4>
<p>Fijemos <span class="math inline">\(a,b\in F\)</span> con <span class="math inline">\(b\ne0\)</span>. Por la Definición 27.1.1 y la Notación 15.3.1 existe un inverso bilateral <span class="math inline">\(b^{-1}\)</span>, con</p>
<p><span class="math display">\[
b\cdot b^{-1}=b^{-1}\cdot b=1. \tag{1}
\]</span></p>
<p><strong>1. Criterio de nulidad.</strong> Si <span class="math inline">\(a=0\)</span>, la absorción del cero (Proposición 14.3.1) da <span class="math inline">\(p=0\cdot b^{-1}=0\)</span>. Recíprocamente, si <span class="math inline">\(p=0\)</span>, multiplicamos <strong>la igualdad</strong> por <span class="math inline">\(b\)</span> a la derecha, sin efectuar ninguna operación sobre desigualdades:</p>
<p><span class="math display">\[
0=0\cdot b=(a\cdot b^{-1})\cdot b
=a\cdot(b^{-1}\cdot b)=a\cdot1=a.
\]</span></p>
<p>Aquí sólo se emplean absorción, asociatividad, la segunda identidad de (1) y la unidad del cuerpo. Obtenemos</p>
<p><span class="math display">\[
a\cdot b^{-1}=0\ \Longleftrightarrow\ a=0. \tag{2}
\]</span></p>
<p>En particular, en cada uno de los cuatro casos de signos estrictos se cumple <span class="math inline">\(a\ne0\)</span> por la definición de <span class="math inline">\(&lt;\)</span>; por (2), tenemos</p>
<p><span class="math display">\[
p\ne0. \tag{3}
\]</span></p>
<p>Esto verifica la no nulidad <strong>local del producto</strong>, en vez de invocar tácitamente una ley global del producto nulo.</p>
<p><strong>2. Signo del inverso.</strong> Si <span class="math inline">\(0&lt;b\)</span>, la Proposición 27.4.1 proporciona <span class="math inline">\(0&lt;b^{-1}\)</span>. Si <span class="math inline">\(b&lt;0\)</span>, la Proposición 27.6.1 proporciona <span class="math inline">\(b^{-1}&lt;0\)</span>. Ninguna regla posterior se aplica antes de establecer estos signos.</p>
<p><strong>3. Los dos casos de igual signo.</strong> Si <span class="math inline">\(0&lt;a\)</span> y <span class="math inline">\(0&lt;b\)</span>, ahora sabemos <span class="math inline">\(0&lt;a\)</span>, <span class="math inline">\(0&lt;b^{-1}\)</span> y <span class="math inline">\(p\ne0\)</span>. La Proposición 26.18.1 sobre productos de positivos, con su hipótesis local de no nulidad verificada en (3), da <span class="math inline">\(0&lt;p\)</span>.</p>
<p>Si <span class="math inline">\(a&lt;0\)</span> y <span class="math inline">\(b&lt;0\)</span>, ahora <span class="math inline">\(a&lt;0\)</span>, <span class="math inline">\(b^{-1}&lt;0\)</span> y <span class="math inline">\(p\ne0\)</span>. El Corolario 26.28.1, aplicado al producto en ese orden y usando (3), da también <span class="math inline">\(0&lt;p\)</span>.</p>
<p><strong>4. Los dos casos de signos opuestos.</strong> Si <span class="math inline">\(0&lt;a\)</span> y <span class="math inline">\(b&lt;0\)</span>, se cumple <span class="math inline">\(0&lt;a\)</span>, <span class="math inline">\(b^{-1}&lt;0\)</span> y <span class="math inline">\(p\ne0\)</span>. El Corolario 26.24.1, en el orden de factores <span class="math inline">\(a,b^{-1}\)</span>, proporciona <span class="math inline">\(p&lt;0\)</span>.</p>
<p>Si <span class="math inline">\(a&lt;0\)</span> y <span class="math inline">\(0&lt;b\)</span>, entonces <span class="math inline">\(a&lt;0\)</span>, <span class="math inline">\(0&lt;b^{-1}\)</span> y <span class="math inline">\(p\ne0\)</span>. La variante del mismo Corolario 26.24.1 para el orden de signos negativo–positivo proporciona igualmente <span class="math inline">\(p&lt;0\)</span>.</p>
<p><strong>5. Producto por la izquierda.</strong> La definición previa de cuerpo incluye conmutatividad multiplicativa. Por ello <span class="math inline">\(b^{-1}a=a b^{-1}=p\)</span>; trasladamos a esta expresión todas las igualdades y desigualdades ya probadas. No se está atribuyendo este cambio de lateralidad a la definición de anillo ordenado, que también admite productos no conmutativos. Quedan probadas todas las afirmaciones. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> El orden de razonamiento importa: primero se comprueba que existe <span class="math inline">\(b^{-1}\)</span>; después se prueba (2), que proporciona <span class="math inline">\(p\ne0\)</span> cuando <span class="math inline">\(a\ne0\)</span>; luego se identifica el signo del inverso; por último se aplican las reglas estrictas de producto, cuyas hipótesis de no nulidad no deben ocultarse.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplos ilustrativos, no premisas.</strong> En los racionales usuales, <span class="math inline">\(2\cdot3^{-1}&gt;0\)</span>, <span class="math inline">\((-2)\cdot(-3)^{-1}&gt;0\)</span>, <span class="math inline">\(2\cdot(-3)^{-1}&lt;0\)</span> y <span class="math inline">\((-2)\cdot3^{-1}&lt;0\)</span>. Si <span class="math inline">\(a=0\)</span> y <span class="math inline">\(b\ne0\)</span>, el producto siempre es cero.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Límite de alcance.</strong> Esta proposición estudia signos de productos por inversos, no la antitonicidad de la inversión entre signos opuestos ni un procedimiento algorítmico para decidir el signo de un elemento arbitrario. No se ha definido todavía una nueva operación de cociente, ni se presupone completitud o propiedad arquimediana.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="multiplicar-por-un-inverso-fijo-preservar-o-invertir-el-orden" class="level2">
<h2 class="anchored" data-anchor-id="multiplicar-por-un-inverso-fijo-preservar-o-invertir-el-orden">27.14. Multiplicar por un inverso fijo: preservar o invertir el orden</h2>
<p>En §27.12 establecimos cómo el signo de un elemento determina el signo de su producto por un inverso. Para <span class="math inline">\(c\ne0\)</span>, fijamos <strong>un mismo multiplicador</strong> <span class="math inline">\(c^{-1}\)</span> y comparamos las imágenes de dos elementos distintos, <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span>. Esta cuestión no es la antitonicidad de la función <span class="math inline">\(x\mapsto x^{-1}\)</span> de §§27.8 y 27.10: aquí <strong>no varía el elemento invertido</strong>.</p>
<p>La hipótesis <span class="math inline">\(c\ne0\)</span> precede a toda aparición de <span class="math inline">\(c^{-1}\)</span>. Su signo se obtiene en §27.4 o §27.6, antes de invocar resultados sobre desigualdades multiplicativas. Para pasar de una comparación estricta a otra, no basta con multiplicar por un elemento de signo conocido en un anillo general: hay que excluir que se anule el producto de la diferencia por ese elemento.</p>
<pre class="text"><code>                  c ≠ 0  ──► existe u = c⁻¹; uc = cu = 1
                    │
           ┌────────┴────────┐
           │                 │
         c &gt; 0             c &lt; 0
           │                 │
         u &gt; 0             u &lt; 0
           │                 │
    a &lt; b  ⇔  au &lt; bu   a &lt; b  ⇔  bu &lt; au
    a &lt; b  ⇔  ua &lt; ub   a &lt; b  ⇔  ub &lt; ua
           └────────┬────────┘
                ambos lados;
           diferencia · u ≠ 0</code></pre>
<section id="talg-pro-00084" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00084">Proposición 27.14.1 — Compatibilidad del orden estricto con la multiplicación por inversos de signo conocido</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c\in F\)</span>. Supongamos, <strong>antes de formar el inverso</strong>, que <span class="math inline">\(c\ne0\)</span>. Entonces se verifican las cuatro equivalencias siguientes, según el signo conocido de <span class="math inline">\(c\)</span>.</p>
<p><strong>I. Factor positivo.</strong> Si <span class="math inline">\(0&lt;c\)</span>, entonces</p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad ac^{-1}&lt;bc^{-1}, \tag{1}
\]</span></p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad c^{-1}a&lt;c^{-1}b. \tag{2}
\]</span></p>
<p><strong>II. Factor negativo.</strong> Si <span class="math inline">\(c&lt;0\)</span>, entonces</p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad bc^{-1}&lt;ac^{-1}, \tag{3}
\]</span></p>
<p><span class="math display">\[
a&lt;b\quad\Longleftrightarrow\quad c^{-1}b&lt;c^{-1}a. \tag{4}
\]</span></p>
<p>Las fórmulas (1)–(4) distinguen la multiplicación por la derecha y por la izquierda. En un cuerpo sus expresiones correspondientes coinciden por conmutatividad, aunque los resultados del capítulo 26 se enunciaron y demostraron con ambas lateralidades independientes. No se define aquí una operación adicional de división.</p>
<section id="talg-prf-00128" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00128">Demostración</h4>
<p><strong>1. Existencia, signo y no nulidad del multiplicador.</strong> Fijemos <span class="math inline">\(c\ne0\)</span>. La Definición 27.1.1 y la Notación 15.3.1 proporcionan el inverso bilateral <span class="math inline">\(u:=c^{-1}\)</span>, con</p>
<p><span class="math display">\[
cu=uc=1. \tag{5}
\]</span></p>
<p>Como <span class="math inline">\(1\ne0\)</span>, necesariamente <span class="math inline">\(u\ne0\)</span>: si <span class="math inline">\(u=0\)</span>, la absorción del cero daría <span class="math inline">\(cu=0\)</span>, en contradicción con (5). Si <span class="math inline">\(0&lt;c\)</span>, la Proposición 27.4.1 establece <span class="math inline">\(0&lt;u\)</span>; si <span class="math inline">\(c&lt;0\)</span>, la Proposición 27.6.1 establece <span class="math inline">\(u&lt;0\)</span>. <strong>No</strong> se infiere el signo de <span class="math inline">\(u\)</span> sin haber establecido primero cuál de estas dos hipótesis rige.</p>
<p><strong>2. Exclusión explícita del producto nulo.</strong> Para las implicaciones que parten de <span class="math inline">\(a&lt;b\)</span>, definamos la diferencia aditiva</p>
<p><span class="math display">\[
d:=b+(-a).
\]</span></p>
<p>La compatibilidad estricta con las traslaciones (Proposición 25.5.1) proporciona <span class="math inline">\(0&lt;d\)</span>, luego <span class="math inline">\(d\ne0\)</span>. Aplicando la Proposición 27.12.1 al numerador <span class="math inline">\(d\)</span> y al elemento no nulo <span class="math inline">\(c\)</span>, su criterio exacto de nulidad da</p>
<p><span class="math display">\[
du=dc^{-1}\ne0. \tag{6}
\]</span></p>
<p>En este punto, y sólo porque la estructura es un <strong>cuerpo conmutativo</strong>, también</p>
<p><span class="math display">\[
ud=du\ne0. \tag{7}
\]</span></p>
<p>Así se satisfacen <strong>por separado</strong> las dos condiciones locales de no nulidad requeridas para obtener desigualdades estrictas por la derecha y por la izquierda. Una justificación alternativa, no necesaria para (6)–(7), es el Teorema 22.3.1: todo cuerpo es un dominio íntegro, por lo que el producto de <span class="math inline">\(d\ne0\)</span> por <span class="math inline">\(u\ne0\)</span> no se anula en ningún orden.</p>
<p><strong>3. Caso positivo: ambas implicaciones y lateralidades.</strong> Supongamos <span class="math inline">\(0&lt;c\)</span>. Por el paso 1, <span class="math inline">\(0&lt;u\)</span>. Si <span class="math inline">\(a&lt;b\)</span>, el criterio local <strong>derecho</strong> de la Proposición 26.30.1, con factor <span class="math inline">\(u\)</span> y condición <span class="math inline">\(du\ne0\)</span> de (6), proporciona <span class="math inline">\(au&lt;bu\)</span>. El criterio <strong>izquierdo</strong> de la misma proposición, ahora con <span class="math inline">\(ud\ne0\)</span> de (7), da <span class="math inline">\(ua&lt;ub\)</span>. Reemplazando <span class="math inline">\(u\)</span> por <span class="math inline">\(c^{-1}\)</span> obtenemos los sentidos directos de (1) y (2).</p>
<p>Recíprocamente, de <span class="math inline">\(au&lt;bu\)</span> y <span class="math inline">\(0&lt;u\)</span>, la <strong>reflexión derecha</strong> de la Proposición 26.30.1 deduce <span class="math inline">\(a&lt;b\)</span>; de <span class="math inline">\(ua&lt;ub\)</span> y <span class="math inline">\(0&lt;u\)</span>, su <strong>reflexión izquierda</strong> deduce igualmente <span class="math inline">\(a&lt;b\)</span>. Estas reflexiones son válidas sin postular de nuevo la no nulidad de productos. Quedan justificadas individualmente las dos direcciones de (1) y de (2).</p>
<p><strong>4. Caso negativo: ambas implicaciones y lateralidades.</strong> Supongamos <span class="math inline">\(c&lt;0\)</span>. El paso 1 establece <span class="math inline">\(u&lt;0\)</span>. Si <span class="math inline">\(a&lt;b\)</span>, el criterio local <strong>derecho</strong> de la Proposición 26.32.1 con <span class="math inline">\(du\ne0\)</span> proporciona <span class="math inline">\(bu&lt;au\)</span>; su criterio <strong>izquierdo</strong>, con <span class="math inline">\(ud\ne0\)</span>, proporciona <span class="math inline">\(ub&lt;ua\)</span>. Son los sentidos directos de (3) y (4).</p>
<p>A la inversa, <span class="math inline">\(bu&lt;au\)</span> y <span class="math inline">\(u&lt;0\)</span> implican <span class="math inline">\(a&lt;b\)</span> por la reflexión derecha de la Proposición 26.32.1. Si <span class="math inline">\(ub&lt;ua\)</span>, se aplica la reflexión izquierda de la misma proposición y se obtiene <span class="math inline">\(a&lt;b\)</span>. La inversión del orden se debe al signo <strong>negativo del factor fijo</strong>, no a la antitonicidad de la función inversa. Con ello se han probado (3) y (4).</p>
<p><strong>5. Comprobación inversa mediante la multiplicación por <span class="math inline">\(c\)</span>.</strong> Podemos verificar adicionalmente los cuatro sentidos recíprocos deshaciendo la multiplicación por <span class="math inline">\(u\)</span>. El Teorema 22.3.1 asegura que, en <span class="math inline">\(F\)</span>, el producto de dos elementos no nulos es no nulo: se cumple, por tanto, la condición global del apartado 4 de las Proposiciones 26.30.1 y 26.32.1. Si <span class="math inline">\(c&gt;0\)</span>, aplicamos la conservación estricta por el factor <span class="math inline">\(c\)</span> a <span class="math inline">\(au&lt;bu\)</span> por la derecha, o a <span class="math inline">\(ua&lt;ub\)</span> por la izquierda; por (5) y asociatividad obtenemos respectivamente</p>
<p><span class="math display">\[
(au)c=a&lt;(bu)c=b,\qquad c(ua)=a&lt;c(ub)=b.
\]</span></p>
<p>Si <span class="math inline">\(c&lt;0\)</span>, aplicamos la inversión estricta por el factor <span class="math inline">\(c\)</span> a <span class="math inline">\(bu&lt;au\)</span> o a <span class="math inline">\(ub&lt;ua\)</span>, respetando la lateralidad:</p>
<p><span class="math display">\[
(au)c=a&lt;(bu)c=b,\qquad c(ua)=a&lt;c(ub)=b.
\]</span></p>
<p>Esta comprobación concuerda con las reflexiones de los pasos 3 y 4; <strong>multiplicar una desigualdad</strong> requiere las hipótesis de orden y de no anulación que acabamos de señalar, mientras que las identidades <span class="math inline">\((au)c=a=c(ua)\)</span> son puramente algebraicas. La igualdad <span class="math inline">\(au=ua\)</span> permite identificar las dos lateralidades en <span class="math inline">\(F\)</span> por conmutatividad, sin atribuir esa propiedad a los anillos ordenados generales. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> El recorrido directo tiene cuatro estaciones: inverso existente, signo del inverso conocido, diferencia <span class="math inline">\(d=b-a\)</span> estrictamente positiva, productos <span class="math inline">\(du\)</span> y <span class="math inline">\(ud\)</span> no nulos. Sólo entonces se aplican los criterios estrictos de 26.30.1 o 26.32.1. El recorrido inverso utiliza las reflexiones ya demostradas; el paso 5 comprueba además que multiplicar por <span class="math inline">\(c\)</span> recupera el orden inicial, con su signo y las condiciones de no anulación explícitos.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo de orientación (no deductivo).</strong> En <span class="math inline">\(\mathbb Q\)</span> con su orden usual, fijemos <span class="math inline">\(a=2\)</span>, <span class="math inline">\(b=5\)</span>. Con <span class="math inline">\(c=3&gt;0\)</span> obtenemos <span class="math inline">\(2\cdot3^{-1}&lt;5\cdot3^{-1}\)</span> y <span class="math inline">\(3^{-1}\cdot2&lt;3^{-1}\cdot5\)</span>. Con <span class="math inline">\(c=-3&lt;0\)</span> obtenemos <span class="math inline">\(5\cdot(-3)^{-1}&lt;2\cdot(-3)^{-1}\)</span> y <span class="math inline">\((-3)^{-1}\cdot5&lt;(-3)^{-1}\cdot2\)</span>: el sentido se invierte.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera y no-ejemplo.</strong> Con <span class="math inline">\(a=b\)</span> los productos de ambos miembros son iguales y ninguna desigualdad estricta aparece, sea cual sea el signo de <span class="math inline">\(c\)</span>. Si <span class="math inline">\(c=0\)</span>, el inverso <span class="math inline">\(c^{-1}\)</span> <strong>no existe</strong>, por lo que (1)–(4) ni siquiera se formulan. En un anillo totalmente ordenado con divisores de cero, el mero signo del multiplicador no garantiza estrictitud: el ejemplo de los números duales del §26.30 muestra productos de una diferencia positiva que se anulan. La hipótesis de cuerpo elimina esa obstrucción; no hemos presupuesto completitud, arquimedianidad ni un algoritmo para decidir comparaciones.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="orden-no-estricto-al-multiplicar-por-un-inverso-de-signo-conocido" class="level2">
<h2 class="anchored" data-anchor-id="orden-no-estricto-al-multiplicar-por-un-inverso-de-signo-conocido">27.16. Orden no estricto al multiplicar por un inverso de signo conocido</h2>
<p>La conservación estricta de la Proposición 27.14.1 no debe trasladarse sin más a la desigualdad no estricta: esta última <strong>admite la igualdad</strong>. Tampoco necesitamos reconstruir el caso general de reflexión de los anillos totalmente ordenados. Para un factor <span class="math inline">\(c\ne0\)</span>, después de multiplicar por su inverso fijo podemos recuperar cada elemento mediante la multiplicación por <span class="math inline">\(c\)</span>: <span class="math inline">\(cc^{-1}=c^{-1}c=1\)</span>.</p>
<p><strong>Pregunta de activación.</strong> Si <span class="math inline">\(a=b\)</span>, ¿qué ocurre al multiplicar ambos miembros por <span class="math inline">\(c^{-1}\)</span>? Los dos productos siguen siendo iguales. Por ello la afirmación correcta emplea <span class="math inline">\(\le\)</span> tanto en la hipótesis como en la conclusión.</p>
<p><strong>Estrategia.</strong> Excluir primero <span class="math inline">\(c=0\)</span>, identificar el signo de <span class="math inline">\(u:=c^{-1}\)</span> mediante las Proposiciones 27.4.1 y 27.6.1, y aplicar las reglas no estrictas de los anillos ordenados: Proposición 26.6.1 para factores no negativos y Proposición 26.8.1 para factores no positivos. Para cada recíproca multiplicar por <span class="math inline">\(c\)</span> en <strong>el mismo lado</strong>, de manera que la identidad inversa suprima el factor. Este argumento no exige ausencia general de productos nulos ni una ley de cancelación obtenida clásicamente.</p>
<section id="talg-pro-00085" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00085">Proposición 27.16.1 — Compatibilidad del orden no estricto con la multiplicación por inversos de signo conocido</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c\in F\)</span>. Supongamos <strong>antes de utilizar la notación de inverso</strong> que <span class="math inline">\(c\ne0\)</span>. Entonces:</p>
<p><strong>I. Si <span class="math inline">\(0&lt;c\)</span>,</strong> se verifican las equivalencias</p>
<p><span class="math display">\[
a\le b\quad\Longleftrightarrow\quad ac^{-1}\le bc^{-1}, \tag{1}
\]</span></p>
<p><span class="math display">\[
a\le b\quad\Longleftrightarrow\quad c^{-1}a\le c^{-1}b. \tag{2}
\]</span></p>
<p><strong>II. Si <span class="math inline">\(c&lt;0\)</span>,</strong> se verifican las equivalencias</p>
<p><span class="math display">\[
a\le b\quad\Longleftrightarrow\quad bc^{-1}\le ac^{-1}, \tag{3}
\]</span></p>
<p><span class="math display">\[
a\le b\quad\Longleftrightarrow\quad c^{-1}b\le c^{-1}a. \tag{4}
\]</span></p>
<p>Se mantienen las dos lateralidades por separado. La conmutatividad del cuerpo permitirá finalmente identificarlas, pero no se usará para deducir una de la otra.</p>
<section id="talg-prf-00129" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00129">Demostración</h4>
<p><strong>1. Inverso bilateral y signos establecidos antes de multiplicar.</strong> Como <span class="math inline">\(c\ne0\)</span>, la definición de cuerpo y la Notación 15.3.1 permiten fijar un inverso <span class="math inline">\(u:=c^{-1}\in F\)</span> que satisface</p>
<p><span class="math display">\[
cu=uc=1. \tag{5}
\]</span></p>
<p>Si <span class="math inline">\(0&lt;c\)</span>, la Proposición 27.4.1 proporciona <span class="math inline">\(0&lt;u\)</span>; por tanto <span class="math inline">\(0\le u\)</span> y <span class="math inline">\(0\le c\)</span>. Si <span class="math inline">\(c&lt;0\)</span>, la Proposición 27.6.1 proporciona <span class="math inline">\(u&lt;0\)</span>; por tanto <span class="math inline">\(u\le0\)</span> y <span class="math inline">\(c\le0\)</span>. Estas conclusiones utilizan la relación entre orden estricto y no estricto de la interfaz de órdenes; <strong>no</strong> presuponen que los signos sean algorítmicamente decidibles.</p>
<p><strong>2. Factor positivo: implicaciones directas.</strong> Supongamos <span class="math inline">\(0&lt;c\)</span> y <span class="math inline">\(a\le b\)</span>. Como <span class="math inline">\(0\le u\)</span>, aplicamos la Proposición 26.6.1 por la derecha y por la izquierda, respectivamente:</p>
<p><span class="math display">\[
au\le bu,\qquad ua\le ub. \tag{6}
\]</span></p>
<p>Al sustituir <span class="math inline">\(u=c^{-1}\)</span>, obtenemos las implicaciones directas de (1) y (2).</p>
<p><strong>3. Factor positivo: implicaciones recíprocas.</strong> Supongamos <span class="math inline">\(au\le bu\)</span>. Puesto que <span class="math inline">\(0\le c\)</span>, la misma Proposición 26.6.1 permite multiplicar <strong>por la derecha</strong>:</p>
<p><span class="math display">\[
(au)c\le(bu)c.
\]</span></p>
<p>La asociatividad y <span class="math inline">\(uc=1\)</span> de (5) reducen esta desigualdad a <span class="math inline">\(a\le b\)</span>. Si, en cambio, suponemos <span class="math inline">\(ua\le ub\)</span>, multiplicamos <strong>por la izquierda</strong> con <span class="math inline">\(c\ge0\)</span>:</p>
<p><span class="math display">\[
c(ua)\le c(ub).
\]</span></p>
<p>Por asociatividad y <span class="math inline">\(cu=1\)</span>, obtenemos nuevamente <span class="math inline">\(a\le b\)</span>. Quedan demostradas ambas direcciones de (1) y (2), sin recurrir a conmutatividad ni a un teorema de cancelación.</p>
<p><strong>4. Factor negativo: implicaciones directas.</strong> Supongamos <span class="math inline">\(c&lt;0\)</span> y <span class="math inline">\(a\le b\)</span>. Como <span class="math inline">\(u\le0\)</span>, la Proposición 26.8.1 invierte el orden al multiplicar por el factor no positivo, con ambas lateralidades:</p>
<p><span class="math display">\[
bu\le au,\qquad ub\le ua. \tag{7}
\]</span></p>
<p>Sustituir <span class="math inline">\(u=c^{-1}\)</span> proporciona las implicaciones directas de (3) y (4).</p>
<p><strong>5. Factor negativo: implicaciones recíprocas.</strong> Si <span class="math inline">\(bu\le au\)</span>, multiplicamos <strong>por la derecha</strong> por <span class="math inline">\(c\le0\)</span> mediante la Proposición 26.8.1, que vuelve a invertir el sentido:</p>
<p><span class="math display">\[
(au)c\le(bu)c.
\]</span></p>
<p>Gracias a <span class="math inline">\(uc=1\)</span>, queda <span class="math inline">\(a\le b\)</span>. Si <span class="math inline">\(ub\le ua\)</span>, multiplicamos <strong>por la izquierda</strong> con el mismo factor negativo:</p>
<p><span class="math display">\[
c(ua)\le c(ub),
\]</span></p>
<p>que se simplifica a <span class="math inline">\(a\le b\)</span> gracias a <span class="math inline">\(cu=1\)</span>. Así se han establecido las cuatro equivalencias. Sólo ahora, por la conmutatividad incluida en la definición de cuerpo, puede añadirse <span class="math inline">\(au=ua\)</span> y <span class="math inline">\(bu=ub\)</span>: esto identifica las formulaciones laterales sin sustituir sus demostraciones. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> En el recorrido directo, el signo del inverso determina si se emplea conservación (26.6.1) o inversión (26.8.1). En el recorrido recíproco se usa el signo de <span class="math inline">\(c\)</span>, <strong>no</strong> el del inverso, y se multiplica en el mismo lado del producto inicial. El efecto de multiplicar dos veces por factores inversos es la identidad, tanto si las dos aplicaciones conservan el orden como si las dos lo invierten.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo orientador, no deductivo.</strong> En <span class="math inline">\(\mathbb Q\)</span> con el orden usual, si <span class="math inline">\(a=1\)</span>, <span class="math inline">\(b=3\)</span> y <span class="math inline">\(c=2\)</span>, (1) da <span class="math inline">\(1/2\le3/2\)</span>. Si <span class="math inline">\(c=-2\)</span>, (3) da <span class="math inline">\(-3/2\le-1/2\)</span>. Los dos ejemplos también satisfacen las correspondientes formulaciones izquierdas.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera.</strong> Si <span class="math inline">\(a=b\)</span>, todos los productos correspondientes coinciden y las cuatro desigualdades no estrictas siguen siendo verdaderas; precisamente por eso la versión estricta no bastaría para cubrir este caso. Si <span class="math inline">\(c=0\)</span>, no existe <span class="math inline">\(c^{-1}\)</span> en un cuerpo y las fórmulas (1)–(4) no se formulan. No aparece aquí una nueva operación de división ni se afirma antitonicidad de la función variable <span class="math inline">\(x\mapsto x^{-1}\)</span>.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="división-convertir-la-multiplicación-por-un-inverso-en-una-función-de-dominio-explícito" class="level2">
<h2 class="anchored" data-anchor-id="división-convertir-la-multiplicación-por-un-inverso-en-una-función-de-dominio-explícito">27.18. División: convertir la multiplicación por un inverso en una función de dominio explícito</h2>
<p>Hemos estudiado los productos <span class="math inline">\(ab^{-1}\)</span> y <span class="math inline">\(b^{-1}a\)</span> sin introducir una operación adicional. Ahora podemos fijar la escritura usual de cociente, pero <strong>sólo después de determinar el conjunto de pares para el cual existe el inverso del denominador</strong>.</p>
<p><strong>Pregunta de activación.</strong> ¿Por qué <span class="math inline">\(0/b\)</span> tiene sentido cuando <span class="math inline">\(b\ne0\)</span>, mientras que <span class="math inline">\(a/0\)</span> no está definido, incluso si <span class="math inline">\(a=0\)</span>? La primera expresión necesita el inverso de <span class="math inline">\(b\)</span>; la segunda exigiría el inverso del cero, inexistente en un cuerpo no trivial.</p>
<section id="talg-def-00062" class="level3">
<h3 class="anchored" data-anchor-id="talg-def-00062">Definición 27.18.1 — División en un cuerpo: dominio de denominadores no nulos y notación</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Por la Proposición 22.2.1, el conjunto de unidades de su anillo subyacente coincide con el conjunto de elementos no nulos:</p>
<p><span class="math display">\[
F^\times=\{b\in F:b\ne0\}=F\setminus\{0\}. \tag{1}
\]</span></p>
<p>Llamaremos <strong>división del cuerpo <span class="math inline">\(F\)</span></strong> a la función</p>
<p><span class="math display">\[
\operatorname{div}_F:F\times F^\times\longrightarrow F,\qquad
\operatorname{div}_F(\langle a,b\rangle):=a\cdot b^{-1}. \tag{2}
\]</span></p>
<p>Para <span class="math inline">\(a,b\in F\)</span> <strong>con <span class="math inline">\(b\ne0\)</span></strong>, adoptamos la notación</p>
<p><span class="math display">\[
\boxed{\displaystyle \frac{a}{b}:=\operatorname{div}_F(\langle a,b\rangle)=a\cdot b^{-1}.} \tag{3}
\]</span></p>
<p>La expresión <span class="math inline">\(a/b\)</span> designa así un elemento de <span class="math inline">\(F\)</span>. La aplicación es <strong>total sobre el dominio restringido</strong> <span class="math inline">\(F\times F^\times\)</span> y no está definida sobre <span class="math inline">\(F\times F\)</span> entero; si <span class="math inline">\(b=0\)</span>, el par <span class="math inline">\(\langle a,b\rangle\)</span> no pertenece a su dominio. El numerador puede ser cualquier elemento de <span class="math inline">\(F\)</span>, incluido <span class="math inline">\(0\)</span>.</p>
<p><strong>Verificación definicional del tipado.</strong> Por (1), cada denominador admisible es una unidad, y la Notación 15.3.1 le asigna un único inverso multiplicativo <span class="math inline">\(b^{-1}\in F\)</span>. El cierre de la multiplicación de un cuerpo garantiza <span class="math inline">\(a\cdot b^{-1}\in F\)</span>. Por tanto, la regla (2) asigna un único valor del codominio a cada par de su dominio y determina una función conforme a la interfaz fundacional de pares y funciones. No se eligen inversos de una familia de conjuntos: la unicidad ya está demostrada, y <strong>Choice no interviene</strong>.</p>
<blockquote class="blockquote">
<p><strong>No confundir dos construcciones.</strong> La Notación 24.3.2 ya emplea <span class="math inline">\(a/b\)</span> para la <em>clase de equivalencia</em> <span class="math inline">\([a,b]_D\in\operatorname{Frac}(D)\)</span> de un par fraccionario de un dominio íntegro <span class="math inline">\(D\)</span>. En (3), en cambio, <span class="math inline">\(a,b\in F\)</span> y <span class="math inline">\(a/b\)</span> es el producto <span class="math inline">\(ab^{-1}\)</span> calculado <strong>dentro de un cuerpo ya dado</strong>. El tipo de los operandos y la construcción indicada por el contexto distinguen ambos usos. No se identifica literalmente una clase de pares con un elemento de <span class="math inline">\(D\)</span>, ni se presupone aquí un teorema de compatibilidad con la inmersión <span class="math inline">\(\iota_D\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo orientador, no premisa.</strong> En <span class="math inline">\(\mathbb Q\)</span>, <span class="math inline">\(6/3=6\cdot3^{-1}=2\)</span> y <span class="math inline">\(0/3=0\)</span>; en cambio <span class="math inline">\(6/0\)</span> y <span class="math inline">\(0/0\)</span> no son valores de <span class="math inline">\(\operatorname{div}_{\mathbb Q}\)</span>. Que un numerador sea cero no subsana un denominador inadmisible.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> Primero se verifica el tipo <span class="math inline">\(\langle a,b\rangle\in F\times F^\times\)</span>; luego se toma el único inverso multiplicativo de <span class="math inline">\(b\)</span>; finalmente se aplica la multiplicación del cuerpo. Las equivalencias de orden de §§27.14 y 27.16 pueden reescribirse con la barra sólo después de esta definición, sin generar nuevos teoremas.</p>
</blockquote>
<hr>
</section>
</section>
<section id="las-identidades-de-división-son-teoremas-sobre-inversos" class="level2">
<h2 class="anchored" data-anchor-id="las-identidades-de-división-son-teoremas-sobre-inversos">27.20. Las identidades de división son teoremas sobre inversos</h2>
<p>La barra ya tiene un significado preciso: <span class="math inline">\(a/b=ab^{-1}\)</span>, pero escribirla no demuestra por sí solo ninguna ley. Antes de operar con cocientes, probaremos las igualdades que enlazan la división con la multiplicación y delimitaremos su criterio de nulidad.</p>
<p><strong>Pregunta de activación.</strong> ¿Por qué la igualdad <span class="math inline">\(xb=a\)</span> determina un único valor de <span class="math inline">\(x\)</span> cuando <span class="math inline">\(b\ne0\)</span>, mientras que no podemos usar el mismo argumento cuando <span class="math inline">\(b=0\)</span>? En el primer caso existe <span class="math inline">\(b^{-1}\)</span> y podemos recuperar <span class="math inline">\(x\)</span> multiplicando la igualdad por ese inverso; en el segundo caso no está disponible tal operación.</p>
<section id="talg-pro-00086" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00086">Proposición 27.20.1 — Identidades básicas de la división y criterio de nulidad</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para cualesquiera <span class="math inline">\(a,b\in F\)</span> con <strong><span class="math inline">\(b\ne0\)</span></strong>, los cocientes siguientes están definidos y satisfacen:</p>
<p><span class="math display">\[
\boxed{\frac a1=a,} \tag{1}
\]</span></p>
<p><span class="math display">\[
\boxed{\frac0b=0,} \tag{2}
\]</span></p>
<p><span class="math display">\[
\boxed{\frac bb=1,} \tag{3}
\]</span></p>
<p><span class="math display">\[
\boxed{\left(\frac ab\right)b=a.} \tag{4}
\]</span></p>
<p>El <strong>criterio exacto de nulidad</strong> es</p>
<p><span class="math display">\[
\boxed{\frac ab=0\quad\Longleftrightarrow\quad a=0.} \tag{5}
\]</span></p>
<p>Más aún, el cociente es la <strong>única solución</strong> de la ecuación multiplicativa <span class="math inline">\(xb=a\)</span>: para todo <span class="math inline">\(x\in F\)</span>,</p>
<p><span class="math display">\[
\boxed{xb=a\quad\Longleftrightarrow\quad x=\frac ab.} \tag{6}
\]</span></p>
<p>En (1), la expresión <span class="math inline">\(a/1\)</span> está permitida porque el cuerpo es no trivial y <span class="math inline">\(1\ne0\)</span>. En (2)–(6), la hipótesis <span class="math inline">\(b\ne0\)</span> debe permanecer explícita; ninguna identidad asigna significado a <span class="math inline">\(a/0\)</span> o <span class="math inline">\(0/0\)</span>.</p>
<section id="talg-prf-00130" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00130">Demostración</h4>
<p><strong>1. Preparación: todo cociente escrito está definido.</strong> El cuerpo es no trivial por la Definición 27.1.1, de modo que <span class="math inline">\(1\ne0\)</span>. La Proposición 22.2.1 identifica <span class="math inline">\(F^\times=F\setminus\{0\}\)</span>: así, tanto <span class="math inline">\(1\)</span> como el elemento concreto <span class="math inline">\(b\ne0\)</span> son denominadores admisibles para la función de la Definición 27.18.1. Por la notación de inversos multiplicativos, existen <span class="math inline">\(1^{-1},b^{-1}\in F\)</span> y se cumple</p>
<p><span class="math display">\[
1\cdot1^{-1}=1,\qquad b^{-1}b=bb^{-1}=1. \tag{7}
\]</span></p>
<p><strong>2. División por la unidad.</strong> Como <span class="math inline">\(1\)</span> es el neutro multiplicativo, <span class="math inline">\(1\cdot1^{-1}=1^{-1}\)</span>. Combinado con (7), esto da <span class="math inline">\(1^{-1}=1\)</span>; por la definición de cociente,</p>
<p><span class="math display">\[
\frac a1=a\cdot1^{-1}=a\cdot1=a.
\]</span></p>
<p><strong>3. Numerador cero.</strong> La Proposición 14.3.1 (absorción del cero) y la definición de división dan</p>
<p><span class="math display">\[
\frac0b=0\cdot b^{-1}=0.
\]</span></p>
<p><strong>4. División de un elemento por sí mismo.</strong> Por <span class="math inline">\(b\ne0\)</span>, (7) permite escribir</p>
<p><span class="math display">\[
\frac bb=b\cdot b^{-1}=1.
\]</span></p>
<p><strong>5. Recuperación del numerador.</strong> Aplicando sucesivamente la definición, la asociatividad, la identidad inversa bilateral de (7) y la unidad multiplicativa, obtenemos</p>
<p><span class="math display">\[
\left(\frac ab\right)b
=(ab^{-1})b
=a(b^{-1}b)
=a\cdot1=a. \tag{8}
\]</span></p>
<p><strong>6. Criterio de nulidad.</strong> Si <span class="math inline">\(a=0\)</span>, (2) implica <span class="math inline">\(a/b=0\)</span>. Si <span class="math inline">\(a/b=0\)</span>, por (8) y por la absorción del cero,</p>
<p><span class="math display">\[
a=\left(\frac ab\right)b=0\cdot b=0.
\]</span></p>
<p>Esto prueba (5). La equivalencia ya había sido establecida para el producto <span class="math inline">\(ab^{-1}\)</span> en la Proposición 27.12.1; aquí queda reformulada mediante el cociente <strong>ahora definido</strong>, y la verificación anterior hace explícita la recuperación del numerador. No se necesita inferir la nulidad de un factor mediante una regla global de divisores de cero.</p>
<p><strong>7. Existencia y unicidad como solución de <span class="math inline">\(xb=a\)</span>.</strong> La identidad (8) proporciona la solución <span class="math inline">\(x=a/b\)</span>. Recíprocamente, si un <span class="math inline">\(x\in F\)</span> satisface <span class="math inline">\(xb=a\)</span>, multiplicamos <strong>a la derecha por <span class="math inline">\(b^{-1}\)</span></strong> y asociamos:</p>
<p><span class="math display">\[
x=x\cdot1=x(bb^{-1})=(xb)b^{-1}=ab^{-1}=\frac ab.
\]</span></p>
<p>Por tanto, cualquier solución coincide con <span class="math inline">\(a/b\)</span>, lo que demuestra (6). La conclusión se ha obtenido exclusivamente mediante inversos de denominadores no nulos y las leyes algebraicas de cuerpo. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> El orden correcto es verificar el denominador, desplegar <span class="math inline">\(a/b=ab^{-1}\)</span>, asociar productos y aplicar <span class="math inline">\(bb^{-1}=b^{-1}b=1\)</span>. La igualdad (4) reconstruye el numerador, mientras que (6) caracteriza la división como resolución <strong>única</strong> de una ecuación multiplicativa.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo de comprobación, no premisa.</strong> En los racionales usuales, <span class="math inline">\(6/3=2\)</span> porque <span class="math inline">\(2\cdot3=6\)</span>; <span class="math inline">\(0/3=0\)</span> y <span class="math inline">\(3/3=1\)</span>. Nada en este ejemplo define <span class="math inline">\(6/0\)</span> ni <span class="math inline">\(0/0\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Distinción de tipos.</strong> Los cocientes de esta proposición son elementos de <span class="math inline">\(F\)</span>; los símbolos de fracción del capítulo 24 designan clases en <span class="math inline">\(\operatorname{Frac}(D)\)</span>. Las identidades (1)–(6) no afirman igualdad literal entre ambas construcciones.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="los-cocientes-heredan-el-signo-y-el-orden-de-la-multiplicación-por-inversos" class="level2">
<h2 class="anchored" data-anchor-id="los-cocientes-heredan-el-signo-y-el-orden-de-la-multiplicación-por-inversos">27.22. Los cocientes heredan el signo y el orden de la multiplicación por inversos</h2>
<p>Ya se definió el cociente <span class="math inline">\(a/b\)</span> para <span class="math inline">\(b\ne0\)</span> en la Definición 27.18.1. Las reglas de signos de §27.12 y las equivalencias de orden de §§27.14 y 27.16 se formularon deliberadamente para productos por inversos, antes de introducir la barra. Ahora podemos trasladar esos resultados al lenguaje de la división <strong>sin redefinir una operación</strong> ni volver a probar sus lemas estrictos.</p>
<p><strong>Pregunta de activación.</strong> Si comparamos <span class="math inline">\(a/b\)</span> con <span class="math inline">\(c/b\)</span>, ¿qué cambia al reemplazar un denominador positivo por uno negativo? La división es multiplicación por <span class="math inline">\(b^{-1}\)</span>: el primer signo conserva el orden del numerador y el segundo lo invierte. En ambas comparaciones el denominador debe ser el mismo y no nulo.</p>
<section id="talg-pro-00087" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00087">Proposición 27.22.1 — Reglas de signos y comparación de cocientes con denominador de signo conocido</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c\in F\)</span>, con <strong><span class="math inline">\(b\ne0\)</span></strong>. Entonces todas las fracciones siguientes son elementos definidos de <span class="math inline">\(F\)</span> y se cumplen las afirmaciones siguientes.</p>
<p><strong>I. Signo del cociente.</strong> Las cinco combinaciones controladas son:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>signo de <span class="math inline">\(a\)</span></th>
<th>signo de <span class="math inline">\(b\)</span></th>
<th>conclusión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0&lt;a\)</span></td>
<td><span class="math inline">\(0&lt;b\)</span></td>
<td><span class="math inline">\(0&lt;a/b\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a&lt;0\)</span></td>
<td><span class="math inline">\(b&lt;0\)</span></td>
<td><span class="math inline">\(0&lt;a/b\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0&lt;a\)</span></td>
<td><span class="math inline">\(b&lt;0\)</span></td>
<td><span class="math inline">\(a/b&lt;0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(a&lt;0\)</span></td>
<td><span class="math inline">\(0&lt;b\)</span></td>
<td><span class="math inline">\(a/b&lt;0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(a=0\)</span></td>
<td><span class="math inline">\(b\ne0\)</span></td>
<td><span class="math inline">\(a/b=0\)</span></td>
</tr>
</tbody>
</table>
<p>En particular, <span class="math inline">\(a/b=0\Longleftrightarrow a=0\)</span>. Esta última equivalencia es <strong>reutilización</strong> de la Proposición 27.20.1, no un teorema nuevo sobre productos nulos.</p>
<p><strong>II. Comparación estricta, denominador fijo.</strong> Si <span class="math inline">\(0&lt;b\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{a&lt;c\quad\Longleftrightarrow\quad\frac ab&lt;\frac cb.} \tag{1}
\]</span></p>
<p>Si <span class="math inline">\(b&lt;0\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{a&lt;c\quad\Longleftrightarrow\quad\frac cb&lt;\frac ab.} \tag{2}
\]</span></p>
<p><strong>III. Comparación no estricta y caso de igualdad.</strong> Si <span class="math inline">\(0&lt;b\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{a\le c\quad\Longleftrightarrow\quad\frac ab\le\frac cb.} \tag{3}
\]</span></p>
<p>Si <span class="math inline">\(b&lt;0\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{a\le c\quad\Longleftrightarrow\quad\frac cb\le\frac ab.} \tag{4}
\]</span></p>
<p>En cualquiera de los dos casos de signo —y, de hecho, para todo <span class="math inline">\(b\ne0\)</span>—,</p>
<p><span class="math display">\[
\boxed{\frac ab=\frac cb\quad\Longleftrightarrow\quad a=c.} \tag{5}
\]</span></p>
<p>No se afirma ninguna comparación con <strong>denominadores distintos</strong>: expresiones como <span class="math inline">\(a/b\)</span> y <span class="math inline">\(c/d\)</span>, con <span class="math inline">\(b\ne d\)</span>, requieren otro enunciado.</p>
<section id="talg-prf-00131" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00131">Demostración</h4>
<p><strong>1. Control del dominio y traducción.</strong> Como <span class="math inline">\(b\ne0\)</span>, la Definición 27.18.1 garantiza que <span class="math inline">\(a/b,c/b\in F\)</span>. Para los tres elementos <span class="math inline">\(a,b,c\)</span> se tiene, por la misma definición,</p>
<p><span class="math display">\[
\frac ab=ab^{-1},\qquad \frac cb=cb^{-1}. \tag{6}
\]</span></p>
<p>No se necesita ningún inverso de <span class="math inline">\(a\)</span> o <span class="math inline">\(c\)</span>. Todas las sustituciones siguientes son igualdades de elementos de <span class="math inline">\(F\)</span>.</p>
<p><strong>2. Signos.</strong> La Proposición 27.12.1 establece los cuatro signos estrictos de <span class="math inline">\(ab^{-1}\)</span> bajo las correspondientes hipótesis y además prueba <span class="math inline">\(ab^{-1}=0\iff a=0\)</span> con <span class="math inline">\(b\ne0\)</span>. Sustituir (6) transforma exactamente cada una de esas conclusiones en la tabla de I. Alternativamente, la fila <span class="math inline">\(a=0\)</span> y el criterio de nulidad se siguen de la Proposición 27.20.1. Así no se deduce el signo a partir de una comparación informal ni se omite la no nulidad del producto requerida por los resultados de §26.</p>
<p><strong>3. Desigualdades estrictas.</strong> Supongamos primero <span class="math inline">\(0&lt;b\)</span>. La Proposición 27.14.1, aplicada al multiplicador fijo <span class="math inline">\(b^{-1}\)</span>, afirma en ambos sentidos</p>
<p><span class="math display">\[
a&lt;c\quad\Longleftrightarrow\quad ab^{-1}&lt;cb^{-1}.
\]</span></p>
<p>Sustituir (6) demuestra (1). Si, en cambio, <span class="math inline">\(b&lt;0\)</span>, la variante negativa de esa misma proposición afirma</p>
<p><span class="math display">\[
a&lt;c\quad\Longleftrightarrow\quad cb^{-1}&lt;ab^{-1},
\]</span></p>
<p>que por (6) es (2). El trabajo previo de §27.14 ya certificó los signos de los inversos y excluyó los productos nulos necesarios para la estricta desigualdad; no se presume aquí ningún nuevo criterio de cancelación.</p>
<p><strong>4. Desigualdades no estrictas.</strong> La Proposición 27.16.1 proporciona, respectivamente,</p>
<p><span class="math display">\[
0&lt;b\quad\Longrightarrow\quad\bigl(a\le c\iff ab^{-1}\le cb^{-1}\bigr),
\]</span></p>
<p><span class="math display">\[
b&lt;0\quad\Longrightarrow\quad\bigl(a\le c\iff cb^{-1}\le ab^{-1}\bigr).
\]</span></p>
<p>La sustitución de (6) demuestra (3) y (4). Estas fórmulas incluyen <span class="math inline">\(a=c\)</span>; reemplazar <span class="math inline">\(\le\)</span> por <span class="math inline">\(&lt;\)</span> habría excluido indebidamente ese caso.</p>
<p><strong>5. Igualdad.</strong> Si <span class="math inline">\(a=c\)</span>, la definición de cociente da <span class="math inline">\(a/b=c/b\)</span> por sustitución. Recíprocamente, si <span class="math inline">\(a/b=c/b\)</span>, multiplicamos esta <strong>igualdad</strong>, no una desigualdad, por <span class="math inline">\(b\)</span>; la identidad <span class="math inline">\((x/b)b=x\)</span> de la Proposición 27.20.1 da</p>
<p><span class="math display">\[
a=\left(\frac ab\right)b=\left(\frac cb\right)b=c.
\]</span></p>
<p>La deducción sólo exige <span class="math inline">\(b\ne0\)</span>; no necesita elegir entre <span class="math inline">\(b&gt;0\)</span> y <span class="math inline">\(b&lt;0\)</span>. Quedan demostradas las afirmaciones. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> Primero verificar <span class="math inline">\(b\ne0\)</span>; después traducir a <span class="math inline">\(ab^{-1}\)</span>; luego aplicar el resultado previo cuyo cuantificador y sentido corresponden al signo conocido de <span class="math inline">\(b\)</span>. El paso de estricta a no estricta no debe improvisarse: se invoca separadamente la Proposición 27.16.1. La igualdad final se recupera multiplicando por el mismo denominador.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo orientador, no premisa.</strong> En los racionales usuales, <span class="math inline">\(1&lt;3\)</span> produce <span class="math inline">\(1/2&lt;3/2\)</span> cuando el denominador es positivo y <span class="math inline">\(3/(-2)&lt;1/(-2)\)</span> cuando es negativo. Los dos cocientes son valores del mismo cuerpo, no clases fraccionarias identificadas con el numerador.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Caso frontera.</strong> Si <span class="math inline">\(a=c\)</span>, las dos comparaciones estrictas de II son falsas, mientras que las dos comparaciones no estrictas de III son verdaderas. Si <span class="math inline">\(b=0\)</span>, ni (1)–(5) están formuladas: no se define <span class="math inline">\(a/0\)</span>. Con denominadores distintos no basta esta proposición para comparar.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="suma-y-producto-de-cocientes-justificar-primero-el-denominador" class="level2">
<h2 class="anchored" data-anchor-id="suma-y-producto-de-cocientes-justificar-primero-el-denominador">27.24. Suma y producto de cocientes: justificar primero el denominador</h2>
<p>Los cocientes <span class="math inline">\(a/b\)</span> y <span class="math inline">\(c/d\)</span> ya son elementos de <span class="math inline">\(F\)</span> cuando <span class="math inline">\(b\)</span> y <span class="math inline">\(d\)</span> son no nulos. Queremos calcular su suma y su producto mediante una sola división. La operación no puede comenzar escribiendo una nueva barra: <strong>hay que probar que el denominador propuesto <span class="math inline">\(bd\)</span> no se anula</strong>. Esto procede de que todo cuerpo es un dominio íntegro (Teorema 22.3.1), no de una suposición sobre el signo de <span class="math inline">\(b\)</span> o de <span class="math inline">\(d\)</span>.</p>
<p><strong>Pregunta de activación.</strong> ¿Cómo reconocer el valor de un cociente sin transformar explícitamente un producto de inversos? La Proposición 27.20.1 caracteriza <span class="math inline">\(t/e\)</span> como la única solución de <span class="math inline">\(ze=t\)</span> cuando <span class="math inline">\(e\ne0\)</span>. Bastará multiplicar la suma y el producto buscados por <span class="math inline">\(bd\)</span> y recuperar sus numeradores.</p>
<section id="talg-pro-00088" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00088">Proposición 27.24.1 — Suma y producto de cocientes con denominadores no nulos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado. Para cualesquiera <span class="math inline">\(a,b,c,d\in F\)</span> tales que <strong><span class="math inline">\(b\ne0\)</span> y <span class="math inline">\(d\ne0\)</span></strong>, se tiene <span class="math inline">\(bd\ne0\)</span> y, por consiguiente, todos los cocientes de las siguientes identidades están definidos:</p>
<p><span class="math display">\[
\boxed{\frac ab+\frac cd=\frac{ad+bc}{bd}.} \tag{1}
\]</span></p>
<p><span class="math display">\[
\boxed{\frac ab\cdot\frac cd=\frac{ac}{bd}.} \tag{2}
\]</span></p>
<p>Ni <span class="math inline">\(a\)</span> ni <span class="math inline">\(c\)</span> deben ser no nulos; tampoco se exige que <span class="math inline">\(b\)</span> o <span class="math inline">\(d\)</span> tengan signo conocido.</p>
<section id="talg-prf-00132" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00132">Demostración</h4>
<p><strong>1. Control de dominios.</strong> Por <span class="math inline">\(b\ne0\)</span> y <span class="math inline">\(d\ne0\)</span>, la Definición 27.18.1 asegura que <span class="math inline">\(a/b,c/d\in F\)</span>. Como todo cuerpo es un dominio íntegro (Teorema 22.3.1), el producto de dos elementos no nulos no puede ser cero; por tanto,</p>
<p><span class="math display">\[
bd\ne0. \tag{3}
\]</span></p>
<p>La misma definición permite ahora formar <span class="math inline">\((ad+bc)/(bd)\)</span> y <span class="math inline">\((ac)/(bd)\)</span>, ambos elementos de <span class="math inline">\(F\)</span>. Esta comprobación precede a cualquier uso de la Proposición 27.20.1 con denominador <span class="math inline">\(bd\)</span>.</p>
<p><strong>2. Recuperación de los numeradores iniciales.</strong> Pongamos <span class="math inline">\(x=a/b\)</span> e <span class="math inline">\(y=c/d\)</span>. La identidad (4) de la Proposición 27.20.1, aplicada por separado a los dos denominadores originales, proporciona</p>
<p><span class="math display">\[
xb=a,\qquad yd=c. \tag{4}
\]</span></p>
<p><strong>3. Suma.</strong> Por distributividad del anillo (Definición 14.1.1), asociatividad y conmutatividad de la multiplicación del cuerpo (Definición 27.1.1),</p>
<p><span class="math display">\[
\begin{aligned}
(x+y)(bd)
&amp;=x(bd)+y(bd)\\
&amp;=(xb)d+(yd)b\\
&amp;=ad+cb\\
&amp;=ad+bc.
\end{aligned} \tag{5}
\]</span></p>
<p>Puesto que <span class="math inline">\(bd\ne0\)</span>, el criterio de solución única de la Proposición 27.20.1 se aplica a <span class="math inline">\(z(bd)=ad+bc\)</span> y concluye</p>
<p><span class="math display">\[
x+y=\frac{ad+bc}{bd}.
\]</span></p>
<p>Sustituyendo las definiciones de <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> se obtiene (1).</p>
<p><strong>4. Producto.</strong> Nuevamente por asociatividad y conmutatividad multiplicativas,</p>
<p><span class="math display">\[
(xy)(bd)=(xb)(yd)=ac. \tag{6}
\]</span></p>
<p>La misma caracterización única de §27.20, ahora aplicada a <span class="math inline">\(z(bd)=ac\)</span>, da</p>
<p><span class="math display">\[
xy=\frac{ac}{bd},
\]</span></p>
<p>que es (2). Queda demostrada la proposición. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> La prueba separa dos obligaciones distintas: garantizar que cada cociente está definido y demostrar su valor. El paso decisivo no es «cancelar denominadores» informalmente, sino probar una ecuación multiplicativa cuyo coeficiente <span class="math inline">\(bd\)</span> es no nulo y utilizar la unicidad de su solución.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo, no premisa.</strong> En los racionales usuales, <span class="math inline">\(1/2+1/3=(1\cdot3+2\cdot1)/(2\cdot3)=5/6\)</span>, mientras <span class="math inline">\((1/2)(1/3)=1/6\)</span>. Las fórmulas probadas no dependen de este ejemplo ni del orden de <span class="math inline">\(F\)</span>: son leyes algebraicas válidas en cualquier cuerpo, aquí formuladas dentro del capítulo de cuerpos ordenados.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Casos frontera y alcance.</strong> Si <span class="math inline">\(a=0\)</span> o <span class="math inline">\(c=0\)</span>, ambas fórmulas siguen bien definidas. Si <span class="math inline">\(b=0\)</span> o <span class="math inline">\(d=0\)</span>, el enunciado deja de ser aplicable; no asigna valor a una división por cero. No se ha probado todavía la fórmula de un cociente de cocientes ni una regla de comparación entre denominadores distintos. En (1) y (2), las barras representan valores de <span class="math inline">\(F\)</span> conforme a la Definición 27.18.1, no clases del cuerpo de fracciones del capítulo 24. No se usa Choice, completitud, arquimedianidad ni formalización Lean.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="opuestos-y-división-sucesiva-condiciones-de-existencia" class="level2">
<h2 class="anchored" data-anchor-id="opuestos-y-división-sucesiva-condiciones-de-existencia">27.26. Opuestos y división sucesiva: condiciones de existencia</h2>
<p>La suma y el producto de cocientes se obtuvieron en la Proposición 27.24.1. Quedan dos operaciones que no deben confundirse: tomar el <strong>opuesto aditivo</strong> de un cociente y <strong>dividir por otro cociente</strong>. La primera sólo requiere un denominador no nulo; la segunda necesita, además, que el cociente usado como divisor no se anule. Por la Proposición 27.20.1, para <span class="math inline">\(d\ne0\)</span> tenemos <span class="math inline">\(c/d\ne0\)</span> exactamente cuando <span class="math inline">\(c\ne0\)</span>.</p>
<p><strong>Pregunta de activación.</strong> Aunque <span class="math inline">\(c/d\)</span> esté definido porque <span class="math inline">\(d\ne0\)</span>, ¿podemos usarlo siempre como denominador? No: si <span class="math inline">\(c=0\)</span>, entonces <span class="math inline">\(c/d=0\)</span>. La hipótesis adicional <span class="math inline">\(c\ne0\)</span> es indispensable.</p>
<section id="talg-pro-00089" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00089">Proposición 27.26.1 — Opuestos y cocientes sucesivos con denominadores no nulos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c,d\in F\)</span>.</p>
<p><strong>(I) Opuestos.</strong> Si <span class="math inline">\(b\ne0\)</span>, entonces <span class="math inline">\(-b\ne0\)</span> y</p>
<p><span class="math display">\[
\boxed{-\!\left(\frac ab\right)=\frac{-a}{b}=\frac{a}{-b}.} \tag{1}
\]</span></p>
<p><strong>(II) Cocientes sucesivos.</strong> Si <span class="math inline">\(b\ne0\)</span>, <span class="math inline">\(c\ne0\)</span> y <span class="math inline">\(d\ne0\)</span>, se encuentran definidos <span class="math inline">\(a/b\)</span>, <span class="math inline">\(c/d\)</span>, <span class="math inline">\(d/c\)</span>, <span class="math inline">\(ad/(bc)\)</span> y el cociente exterior <span class="math inline">\((a/b)/(c/d)\)</span>. Además,</p>
<p><span class="math display">\[
\boxed{\frac{\,a/b\,}{\,c/d\,}=\frac{ad}{bc}.} \tag{2}
\]</span></p>
<p>En ninguno de los dos apartados se exige <span class="math inline">\(a\ne0\)</span> ni se fija el signo de <span class="math inline">\(b,c,d\)</span>.</p>
<section id="talg-prf-00133" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00133">Demostración</h4>
<p><strong>1. Dominios y opuestos.</strong> Supongamos <span class="math inline">\(b\ne0\)</span>. Si <span class="math inline">\(-b=0\)</span>, la involución del opuesto aditivo en el anillo (Definición 14.1.1) daría <span class="math inline">\(b=-(-b)=-0=0\)</span>, contradicción; por tanto <span class="math inline">\(-b\ne0\)</span>. La Definición 27.18.1 permite formar los tres cocientes involucrados en (1).</p>
<p>Pongamos <span class="math inline">\(x=a/b\)</span>. La identidad <span class="math inline">\((a/b)b=a\)</span> de la Proposición 27.20.1 y las reglas de signos del anillo (Proposición 14.4.1) dan</p>
<p><span class="math display">\[
(-x)b=-(xb)=-a. \tag{3}
\]</span></p>
<p>Como <span class="math inline">\(b\ne0\)</span>, el criterio de solución única <span class="math inline">\(zb=-a\iff z=(-a)/b\)</span> de la Proposición 27.20.1 muestra que <span class="math inline">\(-x=(-a)/b\)</span>. Por otra parte,</p>
<p><span class="math display">\[
(-x)(-b)=xb=a. \tag{4}
\]</span></p>
<p>Aquí <span class="math inline">\(-b\ne0\)</span>, de modo que la misma caracterización, aplicada ahora a <span class="math inline">\(z(-b)=a\)</span>, proporciona <span class="math inline">\(-x=a/(-b)\)</span>. Sustituyendo <span class="math inline">\(x=a/b\)</span> obtenemos (1).</p>
<p><strong>2. Dominios de la división sucesiva.</strong> Supongamos además <span class="math inline">\(c\ne0\)</span> y <span class="math inline">\(d\ne0\)</span>. Por la Definición 27.18.1 existen <span class="math inline">\(y=c/d\)</span> y <span class="math inline">\(r=d/c\)</span>. La equivalencia de nulidad de la Proposición 27.20.1, aplicada con <span class="math inline">\(d\ne0\)</span>, implica</p>
<p><span class="math display">\[
y=\frac cd\ne0. \tag{5}
\]</span></p>
<p>Todo cuerpo es un dominio íntegro (Teorema 22.3.1), por lo cual <span class="math inline">\(bc\ne0\)</span> y <span class="math inline">\(cd\ne0\)</span>. Así, tanto <span class="math inline">\(ad/(bc)\)</span> como <span class="math inline">\(dc/(cd)\)</span> están definidos. La propia no nulidad (5) autoriza formar <span class="math inline">\((a/b)/(c/d)\)</span>.</p>
<p><strong>3. El inverso del divisor como cociente.</strong> La regla de producto de la Proposición 27.24.1, con denominadores <span class="math inline">\(c,d\ne0\)</span>, da</p>
<p><span class="math display">\[
ry=\frac dc\cdot\frac cd=\frac{dc}{cd}=\frac{cd}{cd}=1. \tag{6}
\]</span></p>
<p>El penúltimo paso usa la conmutatividad del cuerpo (Definición 27.1.1); el último, la identidad <span class="math inline">\(e/e=1\)</span> de la Proposición 27.20.1, aplicada a <span class="math inline">\(e=cd\ne0\)</span>.</p>
<p><strong>4. Identificación del cociente exterior.</strong> Sea <span class="math inline">\(x=a/b\)</span>. Aplicamos de nuevo la Proposición 27.24.1, ahora a <span class="math inline">\(x\cdot r\)</span>, y obtenemos</p>
<p><span class="math display">\[
xr=\frac ab\cdot\frac dc=\frac{ad}{bc}. \tag{7}
\]</span></p>
<p>Por asociatividad, (6) y la identidad multiplicativa,</p>
<p><span class="math display">\[
(xr)y=x(ry)=x\cdot1=x. \tag{8}
\]</span></p>
<p>Como <span class="math inline">\(y=c/d\ne0\)</span>, el criterio de solución única de la Proposición 27.20.1 caracteriza <span class="math inline">\(x/y\)</span> como el único <span class="math inline">\(z\in F\)</span> que cumple <span class="math inline">\(zy=x\)</span>. La igualdad (8) prueba que ese elemento es <span class="math inline">\(xr\)</span>; (7) concluye</p>
<p><span class="math display">\[
\frac{\,a/b\,}{\,c/d\,}=\frac{ad}{bc}.
\]</span></p>
<p>Quedan demostradas ambas afirmaciones. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> En (I) no se «traslada» informalmente el signo menos: se multiplica cada candidato por su denominador y se usa la unicidad del cociente. En (II), primero se prueba <span class="math inline">\(c/d\ne0\)</span>; después se verifica que <span class="math inline">\((d/c)(c/d)=1\)</span> y sólo entonces se identifica la división exterior con una multiplicación. Son pasos algebraicos, sin suponer signos de los denominadores.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo ilustrativo, no premisa.</strong> En los racionales, <span class="math inline">\(-(2/3)=(-2)/3=2/(-3)\)</span>; además, <span class="math inline">\((2/3)/(4/5)=(2\cdot5)/(3\cdot4)=5/6\)</span>. El ejemplo no sustituye el control de dominios ni la prueba general.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Casos frontera.</strong> <span class="math inline">\(a=0\)</span> es admisible en ambos apartados. Si <span class="math inline">\(b=0\)</span>, no existe el primer cociente; si <span class="math inline">\(d=0\)</span>, no existe <span class="math inline">\(c/d\)</span>; y si <span class="math inline">\(c=0\)</span> con <span class="math inline">\(d\ne0\)</span>, el divisor exterior es exactamente <span class="math inline">\(0\)</span> y la expresión <span class="math inline">\((a/b)/(c/d)\)</span> no está definida. Tampoco se han comparado cocientes de denominadores distintos. Las barras designan elementos de <span class="math inline">\(F\)</span>, no clases de <span class="math inline">\(\operatorname{Frac}(D)\)</span>.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="comparar-cocientes-los-productos-cruzados-y-el-signo-del-factor" class="level2">
<h2 class="anchored" data-anchor-id="comparar-cocientes-los-productos-cruzados-y-el-signo-del-factor">27.28. Comparar cocientes: los productos cruzados y el signo del factor</h2>
<p>Las Proposiciones 27.22.1 y 27.24.1 permiten comparar cocientes con denominador común y operar con cocientes de denominadores distintos. Pero una comparación de <span class="math inline">\(a/b\)</span> con <span class="math inline">\(c/d\)</span> no se decide simplemente «multiplicando en cruz»: hay que conocer el signo de <strong><span class="math inline">\(bd\)</span></strong>, pues multiplicar por un factor negativo invierte el orden. La ventaja de trabajar en un cuerpo es que <span class="math inline">\(b,d\ne0\)</span> implican <span class="math inline">\(bd\ne0\)</span>.</p>
<p><strong>Pregunta de activación.</strong> Si <span class="math inline">\(b&lt;0&lt;d\)</span>, ¿debemos conservar el sentido de <span class="math inline">\(a/b&lt;c/d\)</span> al comparar <span class="math inline">\(ad\)</span> con <span class="math inline">\(bc\)</span>? No: en ese caso el producto <span class="math inline">\(bd\)</span> es negativo y las desigualdades se invierten. En lugar de confiar en una regla mnemotécnica, vamos a recuperar ambos numeradores por multiplicación y aplicar resultados de orden ya demostrados.</p>
<section id="talg-pro-00090" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00090">Proposición 27.28.1 — Comparación de cocientes por productos cruzados con denominadores de signo conocido</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c,d\in F\)</span> con <strong><span class="math inline">\(b\ne0\)</span> y <span class="math inline">\(d\ne0\)</span></strong>. Entonces <span class="math inline">\(bd\ne0\)</span> y ambos cocientes <span class="math inline">\(a/b,c/d\in F\)</span> están definidos. Se verifican las siguientes equivalencias.</p>
<p><strong>(I) Producto positivo.</strong> Si <span class="math inline">\(0&lt;bd\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{\frac ab&lt;\frac cd\ \Longleftrightarrow\ ad&lt;bc,} \tag{1}
\]</span></p>
<p><span class="math display">\[
\boxed{\frac ab\le\frac cd\ \Longleftrightarrow\ ad\le bc.} \tag{2}
\]</span></p>
<p><strong>(II) Producto negativo.</strong> Si <span class="math inline">\(bd&lt;0\)</span>, entonces</p>
<p><span class="math display">\[
\boxed{\frac ab&lt;\frac cd\ \Longleftrightarrow\ bc&lt;ad,} \tag{3}
\]</span></p>
<p><span class="math display">\[
\boxed{\frac ab\le\frac cd\ \Longleftrightarrow\ bc\le ad.} \tag{4}
\]</span></p>
<p><strong>(III) Igualdad, sin hipótesis de signo.</strong> Para todo <span class="math inline">\(b,d\ne0\)</span>,</p>
<p><span class="math display">\[
\boxed{\frac ab=\frac cd\ \Longleftrightarrow\ ad=bc.} \tag{5}
\]</span></p>
<p>La condición de signo se impone al <strong>producto <span class="math inline">\(bd\)</span></strong>, no a los numeradores. No se exige <span class="math inline">\(a\ne0\)</span> ni <span class="math inline">\(c\ne0\)</span>; el criterio (5) tampoco exige conocer qué signo tiene <span class="math inline">\(bd\)</span>.</p>
<section id="talg-prf-00134" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00134">Demostración</h4>
<p><strong>1. Definición y no nulidad.</strong> Fijemos <span class="math inline">\(a,b,c,d\in F\)</span> con <span class="math inline">\(b,d\ne0\)</span>. Por la Definición 27.18.1 existen los elementos</p>
<p><span class="math display">\[
x:=\frac ab,\qquad y:=\frac cd.
\]</span></p>
<p>Como todo cuerpo es un dominio íntegro (Teorema 22.3.1), el producto</p>
<p><span class="math display">\[
t:=bd\ne0. \tag{6}
\]</span></p>
<p>La definición de cuerpo incluye la estructura de anillo conmutativo (Definiciones 14.1.1 y 27.1.1). Por recuperación de los numeradores (Proposición 27.20.1), <span class="math inline">\(xb=a\)</span> y <span class="math inline">\(yd=c\)</span>. Asociamos y reordenamos los factores para obtener, sin dividir por nada nuevo,</p>
<p><span class="math display">\[
xt=(xb)d=ad,\qquad yt=(yd)b=cb=bc. \tag{7}
\]</span></p>
<p>Estas dos identidades justifican <strong>toda</strong> la comparación cruzada posterior: los productos <span class="math inline">\(ad\)</span> y <span class="math inline">\(bc\)</span> no son recetas independientes, sino <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> multiplicados por el <strong>mismo factor no nulo</strong> <span class="math inline">\(t\)</span>.</p>
<p><strong>Regularidad derecha del factor.</strong> Si <span class="math inline">\(zt=0\)</span>, tanto <span class="math inline">\(z\)</span> como <span class="math inline">\(0\)</span> resuelven <span class="math inline">\(wt=0\)</span>. Como <span class="math inline">\(t\ne0\)</span>, la unicidad de la solución en la Proposición 27.20.1 da <span class="math inline">\(z=0\)</span>. Por tanto <span class="math inline">\(t\)</span> satisface la hipótesis de regularidad derecha de la Proposición 26.34.1. Usaremos esa variante, cuya cancelación no requiere eliminación de doble negación.</p>
<p><strong>2. Caso <span class="math inline">\(0&lt;t\)</span>.</strong> La Proposición 26.30.1 establece que, en un anillo totalmente ordenado sin productos nulos de factores no nulos, multiplicar por un factor positivo preserva y refleja el orden estricto. La hipótesis global de esa proposición se satisface por el Teorema 22.3.1. Por tanto,</p>
<p><span class="math display">\[
x&lt;y\quad\Longleftrightarrow\quad xt&lt;yt
\quad\stackrel{(7)}{\Longleftrightarrow}\quad ad&lt;bc.
\]</span></p>
<p>Ésta es (1). Para el orden no estricto, la Proposición 26.34.1 —aplicada al mismo anillo, al mismo factor positivo y a la regularidad derecha que acabamos de demostrar— da</p>
<p><span class="math display">\[
x\le y\quad\Longleftrightarrow\quad xt\le yt
\quad\stackrel{(7)}{\Longleftrightarrow}\quad ad\le bc,
\]</span></p>
<p>que demuestra (2).</p>
<p><strong>3. Caso <span class="math inline">\(t&lt;0\)</span>.</strong> La Proposición 26.32.1 proporciona, bajo la misma condición global de no anulación, la equivalencia estricta con sentido invertido:</p>
<p><span class="math display">\[
x&lt;y\quad\Longleftrightarrow\quad yt&lt;xt
\quad\stackrel{(7)}{\Longleftrightarrow}\quad bc&lt;ad.
\]</span></p>
<p>La variante negativa de la Proposición 26.34.1, bajo esa misma regularidad derecha, proporciona la equivalencia no estricta</p>
<p><span class="math display">\[
x\le y\quad\Longleftrightarrow\quad yt\le xt
\quad\stackrel{(7)}{\Longleftrightarrow}\quad bc\le ad.
\]</span></p>
<p>Éstas son (3) y (4). En ningún paso se ha multiplicado una desigualdad por un factor de signo desconocido.</p>
<p><strong>4. Igualdad sin distinguir signos.</strong> Si <span class="math inline">\(x=y\)</span>, la sustitución en (7) produce <span class="math inline">\(ad=bc\)</span>. En sentido recíproco, supongamos <span class="math inline">\(ad=bc\)</span>. Entonces (7) implica <span class="math inline">\(xt=yt=ad\)</span>. Puesto que <span class="math inline">\(t\ne0\)</span>, la caracterización única de la solución de <span class="math inline">\(zt=ad\)</span> en la Proposición 27.20.1 obliga a que <span class="math inline">\(x=y\)</span>. Sustituyendo sus definiciones se obtiene (5), sin realizar ninguna comparación de signos. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> Compruébese primero <span class="math inline">\(b\ne0\)</span>, <span class="math inline">\(d\ne0\)</span> y <span class="math inline">\(bd\ne0\)</span>. Después, las igualdades <span class="math inline">\(\bigl(a/b\bigr)(bd)=ad\)</span> y <span class="math inline">\(\bigl(c/d\bigr)(bd)=bc\)</span> reducen el problema a comparar <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> tras multiplicarlos por un único factor <span class="math inline">\(bd\)</span>. Las Proposiciones 26.30.1, 26.32.1 y 26.34.1 ya contienen las dos direcciones de las equivalencias; la ausencia de divisores de cero evita perder la estrictitud.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Dos ejemplos, no premisas.</strong> Con denominadores positivos, <span class="math inline">\(1/2&lt;2/3\)</span> se lee <span class="math inline">\(1\cdot3&lt;2\cdot2\)</span>. Con denominadores de signo contrario, <span class="math inline">\(1/(-2)&lt;1/3\)</span> se lee <span class="math inline">\((-2)\cdot1&lt;1\cdot3\)</span>, es decir, <span class="math inline">\(bc&lt;ad\)</span>: la comparación cruzada invierte su dirección. En ambos ejemplos el denominador exterior común es el producto <span class="math inline">\(bd\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Errores y casos frontera.</strong> No se puede afirmar <span class="math inline">\(a/b&lt;c/d\iff ad&lt;bc\)</span> sin controlar <span class="math inline">\(bd\)</span>: si <span class="math inline">\(bd&lt;0\)</span>, la fórmula correcta es (3). Si <span class="math inline">\(b=0\)</span> o <span class="math inline">\(d=0\)</span>, las expresiones iniciales no están definidas; por el contrario, <span class="math inline">\(a=0\)</span> o <span class="math inline">\(c=0\)</span> es admisible. La igualdad (5) no requiere signo, pero sí exige ambos denominadores no nulos. Los cocientes designan elementos del cuerpo <span class="math inline">\(F\)</span>, no clases de <span class="math inline">\(\operatorname{Frac}(D)\)</span> del capítulo 24.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="amplificar-y-simplificar-un-cociente-el-factor-común-debe-ser-no-nulo" class="level2">
<h2 class="anchored" data-anchor-id="amplificar-y-simplificar-un-cociente-el-factor-común-debe-ser-no-nulo">27.30. Amplificar y simplificar un cociente: el factor común debe ser no nulo</h2>
<p>La regla escolar de «multiplicar numerador y denominador por el mismo número» sólo es correcta bajo una condición que aquí no puede quedar implícita: el factor añadido al denominador debe ser <strong>no nulo</strong>. Si se multiplicara por <span class="math inline">\(0\)</span>, el nuevo denominador sería <span class="math inline">\(0\)</span> y la expresión dejaría de pertenecer al dominio de la división definido en §27.18.</p>
<p><strong>Pregunta de activación.</strong> Si <span class="math inline">\(a/b\)</span> ya está definido porque <span class="math inline">\(b\ne0\)</span>, ¿por qué no podemos escribir también <span class="math inline">\(a/b=(a\cdot0)/(b\cdot0)\)</span>? Porque la segunda barra exigiría dividir por <span class="math inline">\(b\cdot0=0\)</span>. La igualdad intuitiva «<span class="math inline">\(0/0\)</span>» no es una fracción permitida en el cuerpo.</p>
<section id="talg-pro-00091" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00091">Proposición 27.30.1 — Amplificación y simplificación de cocientes por factores no nulos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,k\in F\)</span> con</p>
<p><span class="math display">\[
b\ne0,\qquad k\ne0.
\]</span></p>
<p>Entonces <span class="math inline">\(bk\ne0\)</span>, ambos cocientes siguientes están definidos y</p>
<p><span class="math display">\[
\boxed{\frac ab=\frac{ak}{bk}.} \tag{1}
\]</span></p>
<p>Leída de izquierda a derecha, (1) es la <strong>amplificación</strong> del cociente por el factor no nulo <span class="math inline">\(k\)</span>; leída de derecha a izquierda, es la <strong>simplificación</strong> de un factor común no nulo. No se exige <span class="math inline">\(a\ne0\)</span> ni se impone signo alguno a <span class="math inline">\(b\)</span> o a <span class="math inline">\(k\)</span>.</p>
<section id="talg-prf-00135" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00135">Demostración</h4>
<p><strong>1. Comprobar el dominio antes de formar el cociente amplificado.</strong> Por hipótesis, <span class="math inline">\(b\ne0\)</span> y <span class="math inline">\(k\ne0\)</span>. Todo cuerpo es un dominio íntegro (Teorema 22.3.1), de modo que el producto de dos elementos no nulos no puede ser cero. Por tanto,</p>
<p><span class="math display">\[
bk\ne0. \tag{2}
\]</span></p>
<p>La Definición 27.18.1 garantiza así que tanto <span class="math inline">\(a/b\)</span> como <span class="math inline">\((ak)/(bk)\)</span> están definidos.</p>
<p><strong>2. Recuperar el numerador del cociente original.</strong> Pongamos</p>
<p><span class="math display">\[
x:=\frac ab.
\]</span></p>
<p>La identidad fundamental de la Proposición 27.20.1 da</p>
<p><span class="math display">\[
xb=a. \tag{3}
\]</span></p>
<p><strong>3. Multiplicar una igualdad, no una desigualdad.</strong> Multiplicamos ambos miembros de (3) por <span class="math inline">\(k\)</span> a la derecha:</p>
<p><span class="math display">\[
(xb)k=ak. \tag{4}
\]</span></p>
<p>Por asociatividad de la multiplicación del anillo (Definición 14.1.1),</p>
<p><span class="math display">\[
x(bk)=ak. \tag{5}
\]</span></p>
<p>No se necesita conocer el signo de <span class="math inline">\(k\)</span>: estamos preservando una <strong>igualdad</strong>, no el sentido de una desigualdad.</p>
<p><strong>4. Usar la caracterización única del cociente.</strong> Como <span class="math inline">\(bk\ne0\)</span> por (2), la Proposición 27.20.1 aplicada ahora al denominador <span class="math inline">\(bk\)</span> afirma que la ecuación</p>
<p><span class="math display">\[
z(bk)=ak
\]</span></p>
<p>tiene una única solución, precisamente</p>
<p><span class="math display">\[
z=\frac{ak}{bk}.
\]</span></p>
<p>Pero (5) muestra que <span class="math inline">\(x\)</span> es una solución de esa ecuación. Por unicidad,</p>
<p><span class="math display">\[
x=\frac{ak}{bk}.
\]</span></p>
<p>Sustituyendo <span class="math inline">\(x=a/b\)</span> obtenemos (1). <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> La demostración no comienza «cancelando <span class="math inline">\(k\)</span>». Primero prueba que <span class="math inline">\(bk\)</span> es un denominador legítimo; después transforma la identidad ya conocida <span class="math inline">\((a/b)b=a\)</span> en <span class="math inline">\(\bigl(a/b\bigr)(bk)=ak\)</span>; finalmente utiliza la unicidad de la solución de <span class="math inline">\(z(bk)=ak\)</span>. La simplificación es, por tanto, la lectura inversa de una igualdad previamente demostrada.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo ilustrativo, no premisa.</strong> En los racionales usuales, <span class="math inline">\(2/3=(2\cdot5)/(3\cdot5)=10/15\)</span>. El papel matemático de <span class="math inline">\(5\)</span> no es que sea positivo, sino que sea no nulo. El mismo resultado vale con <span class="math inline">\(k=-5\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Error típico y casos frontera.</strong> El paso <span class="math inline">\(a/b=(ak)/(bk)\)</span> es inválido si <span class="math inline">\(k=0\)</span>, porque el denominador derecho se vuelve <span class="math inline">\(0\)</span>. En cambio, <span class="math inline">\(a=0\)</span> no causa dificultad: si <span class="math inline">\(b,k\ne0\)</span>, entonces <span class="math inline">\(0/b=0/(bk)=0\)</span>. Tampoco se requiere que <span class="math inline">\(b\)</span> y <span class="math inline">\(k\)</span> tengan el mismo signo.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="normalizar-el-signo-del-denominador" class="level2">
<h2 class="anchored" data-anchor-id="normalizar-el-signo-del-denominador">27.32. Normalizar el signo del denominador</h2>
<p>Un cociente puede estar perfectamente definido y, sin embargo, aparecer con denominador negativo. Para las comparaciones posteriores resulta conveniente saber que ese signo puede trasladarse simultáneamente al numerador y al denominador, de modo que el denominador quede positivo. Esta operación no crea una «fracción reducida» ni una representación canónica: sólo normaliza el <strong>signo</strong> del denominador.</p>
<p><strong>Pregunta de activación.</strong> Si únicamente sabemos que <span class="math inline">\(b\ne0\)</span>, ¿podemos decidir sin más que <span class="math inline">\(b&gt;0\)</span> o que <span class="math inline">\(b&lt;0\)</span>? Matemáticamente sí obtenemos una disyunción a partir de la totalidad del orden y la no nulidad de <span class="math inline">\(b\)</span>; eso no proporciona por sí mismo un algoritmo que determine cuál de las dos alternativas ocurre.</p>
<section id="talg-pro-00092" class="level3">
<h3 class="anchored" data-anchor-id="talg-pro-00092">Proposición 27.32.1 — Normalización de cocientes a denominador positivo</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b\in F\)</span> con <span class="math inline">\(b\ne0\)</span>. Entonces exactamente una de las dos situaciones siguientes ocurre:</p>
<ol type="1">
<li><span class="math inline">\(0&lt;b\)</span>, y el cociente <span class="math inline">\(a/b\)</span> ya tiene denominador positivo;</li>
<li><span class="math inline">\(b&lt;0\)</span>, en cuyo caso <span class="math display">\[
0&lt;-b
\]</span> y <span class="math display">\[
\boxed{\frac ab=\frac{-a}{-b}.} \tag{1}
\]</span></li>
</ol>
<p>En particular, existen <span class="math inline">\(n,d\in F\)</span> tales que</p>
<p><span class="math display">\[
0&lt;d
\qquad\text{y}\qquad
\boxed{\frac ab=\frac nd.} \tag{2}
\]</span></p>
<p>El enunciado (2) es existencial: no afirma que el par <span class="math inline">\((n,d)\)</span> sea único ni que el orden de <span class="math inline">\(F\)</span> disponga de un procedimiento algorítmico para escoger entre los dos casos.</p>
<section id="talg-prf-00136" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00136">Demostración</h4>
<p><strong>1. El cociente inicial está definido.</strong> La hipótesis <span class="math inline">\(b\ne0\)</span> coloca a <span class="math inline">\(b\)</span> en el dominio permitido por la Definición 27.18.1. Por tanto,</p>
<p><span class="math display">\[
\frac ab\in F
\]</span></p>
<p>está definido antes de efectuar cualquier transformación de signos.</p>
<p><strong>2. Obtener los dos casos desde la totalidad, sin postular tricotomía.</strong> Como el orden de <span class="math inline">\(F\)</span> es total, aplicado a <span class="math inline">\(0\)</span> y <span class="math inline">\(b\)</span> proporciona la disyunción</p>
<p><span class="math display">\[
0\le b\quad\lor\quad b\le0. \tag{3}
\]</span></p>
<p>Supongamos primero <span class="math inline">\(0\le b\)</span>. Si <span class="math inline">\(0=b\)</span>, la simetría de la igualdad daría <span class="math inline">\(b=0\)</span>, contradicción. Luego <span class="math inline">\(0\ne b\)</span> y, por la definición de orden estricto de la Interfaz 25.1.1,</p>
<p><span class="math display">\[
0&lt;b. \tag{4}
\]</span></p>
<p>Supongamos ahora <span class="math inline">\(b\le0\)</span>. Junto con la hipótesis <span class="math inline">\(b\ne0\)</span>, la misma definición de orden estricto da directamente</p>
<p><span class="math display">\[
b&lt;0. \tag{5}
\]</span></p>
<p>Así, (3) se ha refinado a la disyunción</p>
<p><span class="math display">\[
0&lt;b\quad\lor\quad b&lt;0. \tag{6}
\]</span></p>
<p>No hemos importado una proposición general de tricotomía: sólo usamos totalidad y la no nulidad concreta del denominador.</p>
<p><strong>3. Normalizar el caso negativo.</strong> Supongamos <span class="math inline">\(b&lt;0\)</span>. La Proposición 25.5.1, aplicada al grupo aditivo subyacente, invierte el orden estricto al tomar opuestos:</p>
<p><span class="math display">\[
-0&lt;-b.
\]</span></p>
<p>En todo grupo aditivo, el opuesto del neutro es el propio neutro; por tanto,</p>
<p><span class="math display">\[
0&lt;-b. \tag{7}
\]</span></p>
<p>En particular, <span class="math inline">\(-b\ne0\)</span>, de modo que el cociente con denominador <span class="math inline">\(-b\)</span> está definido.</p>
<p>Para justificar la igualdad de cocientes no moveremos signos de manera informal. Aplicamos la Proposición 27.26.1 al numerador <span class="math inline">\(-a\)</span> y al denominador <span class="math inline">\(b\ne0\)</span>. Su identidad de opuestos afirma</p>
<p><span class="math display">\[
-\!\left(\frac{-a}{b}\right)
=
\frac{-(-a)}{b}
=
\frac{-a}{-b}. \tag{8}
\]</span></p>
<p>La involución del opuesto aditivo convierte el término central en <span class="math inline">\(a/b\)</span>, y por tanto (8) da exactamente</p>
<p><span class="math display">\[
\frac ab=\frac{-a}{-b}. \tag{9}
\]</span></p>
<p>Combinando (7) y (9), el denominador normalizado es positivo.</p>
<p><strong>4. Construir los testigos de (2).</strong> Si ocurre el primer caso de (6), tomamos</p>
<p><span class="math display">\[
n:=a,\qquad d:=b.
\]</span></p>
<p>Entonces <span class="math inline">\(0&lt;d\)</span> por (4) y <span class="math inline">\(a/b=n/d\)</span> por sustitución.</p>
<p>Si ocurre el segundo caso, tomamos</p>
<p><span class="math display">\[
n:=-a,\qquad d:=-b.
\]</span></p>
<p>Entonces <span class="math inline">\(0&lt;d\)</span> por (7) y <span class="math inline">\(a/b=n/d\)</span> por (9). En ambos casos existen los testigos requeridos.</p>
<p><strong>5. Exclusión mutua de los dos signos.</strong> Si simultáneamente <span class="math inline">\(0&lt;b\)</span> y <span class="math inline">\(b&lt;0\)</span>, la definición del orden estricto proporciona <span class="math inline">\(0\le b\)</span> y <span class="math inline">\(b\le0\)</span>. Por antisimetría,</p>
<p><span class="math display">\[
0=b,
\]</span></p>
<p>contradiciendo <span class="math inline">\(b\ne0\)</span>. Por ello las dos alternativas son mutuamente excluyentes. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> La prueba separa tres tareas que suelen comprimirse en una regla escolar: primero obtiene el signo del denominador desde totalidad más no nulidad; después demuestra que cambiar simultáneamente ambos signos conserva el cociente; sólo al final elige los testigos con denominador positivo. Ningún paso presupone una función de signo computable.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo ilustrativo, no premisa.</strong> En los racionales usuales, <span class="math inline">\(2/(-3)=(-2)/3\)</span>. El segundo denominador es positivo, pero el valor del cociente no cambió. Si el denominador ya era positivo, como en <span class="math inline">\(2/3\)</span>, no hay nada que modificar.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Qué significa aquí «normalizar».</strong> La normalización afecta únicamente al signo del denominador. No se ha definido máximo común divisor, coprimalidad, «fracción irreducible» ni una representación canónica del elemento de <span class="math inline">\(F\)</span>. La Proposición 27.30.1 muestra, de hecho, que un mismo cociente admite amplificaciones por factores no nulos.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Casos frontera y alcance.</strong> El numerador puede ser <span class="math inline">\(0\)</span>; entonces también <span class="math inline">\(-a=0\)</span> y la normalización funciona sin excepción. El denominador <span class="math inline">\(0\)</span> queda excluido desde el inicio. No se usa Choice, una tricotomía importada, decidibilidad del orden, completitud, arquimedianidad, algoritmos ni formalización Lean.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="comparar-después-de-normalizar-un-único-sentido-de-cruce" class="level2">
<h2 class="anchored" data-anchor-id="comparar-después-de-normalizar-un-único-sentido-de-cruce">27.34. Comparar después de normalizar: un único sentido de cruce</h2>
<p>La Proposición 27.32.1 permite representar cada cociente con denominador positivo. Una vez hecho esto, la bifurcación de §27.28 desaparece: el producto de dos denominadores positivos vuelve a ser positivo, de modo que la comparación cruzada conserva siempre el sentido del orden.</p>
<p><strong>Pregunta de activación.</strong> Si dos cocientes admiten muchas representaciones con denominador positivo, ¿depende la comparación del par de representaciones elegido? No.&nbsp;Cada representación positiva satisface por separado el mismo criterio de productos cruzados, porque la Proposición 27.28.1 se aplica a cualquiera de ellas.</p>
<section id="talg-cor-00020" class="level3">
<h3 class="anchored" data-anchor-id="talg-cor-00020">Corolario 27.34.1 — Reducción de comparaciones de cocientes a denominadores positivos</h3>
<p>Sea <span class="math inline">\(\langle F,+,\cdot,\le\rangle\)</span> un cuerpo ordenado y sean <span class="math inline">\(a,b,c,d\in F\)</span> con</p>
<p><span class="math display">\[
b\ne0,\qquad d\ne0.
\]</span></p>
<p>Entonces existen <span class="math inline">\(n_1,e_1,n_2,e_2\in F\)</span> tales que</p>
<p><span class="math display">\[
0&lt;e_1,\qquad 0&lt;e_2, \tag{1}
\]</span></p>
<p><span class="math display">\[
\frac ab=\frac{n_1}{e_1},
\qquad
\frac cd=\frac{n_2}{e_2}. \tag{2}
\]</span></p>
<p>Además, <strong>para cualesquiera</strong> <span class="math inline">\(n_1,e_1,n_2,e_2\)</span> que satisfagan (1) y (2), se verifican simultáneamente</p>
<p><span class="math display">\[
\boxed{
\frac ab&lt;\frac cd
\quad\Longleftrightarrow\quad
n_1e_2&lt;n_2e_1,
} \tag{3}
\]</span></p>
<p><span class="math display">\[
\boxed{
\frac ab\le\frac cd
\quad\Longleftrightarrow\quad
n_1e_2\le n_2e_1,
} \tag{4}
\]</span></p>
<p>y</p>
<p><span class="math display">\[
\boxed{
\frac ab=\frac cd
\quad\Longleftrightarrow\quad
n_1e_2=n_2e_1.
} \tag{5}
\]</span></p>
<p>En particular, si los denominadores originales ya son positivos, <span class="math inline">\(0&lt;b\)</span> y <span class="math inline">\(0&lt;d\)</span>, podemos tomar</p>
<p><span class="math display">\[
(n_1,e_1,n_2,e_2)=(a,b,c,d),
\]</span></p>
<p>y (3)–(5) se reducen a las reglas usuales de productos cruzados sin distinguir un caso adicional de signo negativo.</p>
<section id="talg-prf-00137" class="level4">
<h4 class="anchored" data-anchor-id="talg-prf-00137">Demostración</h4>
<p><strong>1. Existencia de representaciones con denominador positivo.</strong> Las hipótesis <span class="math inline">\(b\ne0\)</span> y <span class="math inline">\(d\ne0\)</span> permiten formar los cocientes iniciales por la Definición 27.18.1. Aplicamos la Proposición 27.32.1 primero a <span class="math inline">\(a/b\)</span> y luego a <span class="math inline">\(c/d\)</span>. Obtenemos testigos <span class="math inline">\(n_1,e_1,n_2,e_2\in F\)</span> tales que</p>
<p><span class="math display">\[
0&lt;e_1,\qquad
\frac ab=\frac{n_1}{e_1}, \tag{6}
\]</span></p>
<p><span class="math display">\[
0&lt;e_2,\qquad
\frac cd=\frac{n_2}{e_2}. \tag{7}
\]</span></p>
<p>Estas son exactamente (1) y (2). Se han usado dos testigos locales proporcionados por dos aplicaciones concretas de una proposición existencial; no se ha escogido simultáneamente una representación para una familia arbitraria de cocientes y, por tanto, no interviene Choice.</p>
<p><strong>2. Fijar representaciones positivas arbitrarias.</strong> Para demostrar que el criterio no depende de los testigos particulares obtenidos en el paso 1, fijemos ahora cualesquiera <span class="math inline">\(n_1,e_1,n_2,e_2\)</span> que satisfagan (1) y (2). De <span class="math inline">\(0&lt;e_1\)</span> y <span class="math inline">\(0&lt;e_2\)</span>, la definición de orden estricto implica</p>
<p><span class="math display">\[
e_1\ne0,\qquad e_2\ne0. \tag{8}
\]</span></p>
<p>Como todo cuerpo es un dominio íntegro (Teorema 22.3.1), (8) da</p>
<p><span class="math display">\[
e_1e_2\ne0. \tag{9}
\]</span></p>
<p>Los dos factores son positivos. La Proposición 26.18.1, aplicada con la no nulidad local (9), concluye</p>
<p><span class="math display">\[
0&lt;e_1e_2. \tag{10}
\]</span></p>
<p>Éste es el punto que elimina la bifurcación de signo de §27.28: el factor común usado para la comparación cruzada es ahora necesariamente positivo.</p>
<p><strong>3. Comparación estricta.</strong> La Proposición 27.28.1, aplicada a los cocientes <span class="math inline">\(n_1/e_1\)</span> y <span class="math inline">\(n_2/e_2\)</span> y al caso positivo (10), da</p>
<p><span class="math display">\[
\frac{n_1}{e_1}&lt;\frac{n_2}{e_2}
\quad\Longleftrightarrow\quad
n_1e_2&lt;e_1n_2. \tag{11}
\]</span></p>
<p>La estructura de cuerpo es conmutativa, de modo que <span class="math inline">\(e_1n_2=n_2e_1\)</span>. Sustituyendo esta igualdad en (11),</p>
<p><span class="math display">\[
\frac{n_1}{e_1}&lt;\frac{n_2}{e_2}
\quad\Longleftrightarrow\quad
n_1e_2&lt;n_2e_1. \tag{12}
\]</span></p>
<p>Por (2), la sustitución de iguales en la relación <span class="math inline">\(&lt;\)</span> transforma (12) exactamente en (3).</p>
<p><strong>4. Comparación no estricta.</strong> La misma Proposición 27.28.1, bajo la misma positividad (10), proporciona</p>
<p><span class="math display">\[
\frac{n_1}{e_1}\le\frac{n_2}{e_2}
\quad\Longleftrightarrow\quad
n_1e_2\le e_1n_2.
\]</span></p>
<p>Conmutatividad y las igualdades (2) producen inmediatamente</p>
<p><span class="math display">\[
\frac ab\le\frac cd
\quad\Longleftrightarrow\quad
n_1e_2\le n_2e_1,
\]</span></p>
<p>que es (4).</p>
<p><strong>5. Igualdad.</strong> El apartado de igualdad de la Proposición 27.28.1 no necesita hipótesis sobre el signo del producto de denominadores; basta <span class="math inline">\(e_1,e_2\ne0\)</span>, ya probado en (8). Por tanto,</p>
<p><span class="math display">\[
\frac{n_1}{e_1}=\frac{n_2}{e_2}
\quad\Longleftrightarrow\quad
n_1e_2=e_1n_2
\quad\Longleftrightarrow\quad
n_1e_2=n_2e_1.
\]</span></p>
<p>Sustituyendo nuevamente (2) obtenemos (5).</p>
<p><strong>6. Caso de denominadores ya positivos.</strong> Si <span class="math inline">\(0&lt;b\)</span> y <span class="math inline">\(0&lt;d\)</span>, entonces la elección local</p>
<p><span class="math display">\[
n_1=a,\quad e_1=b,\quad n_2=c,\quad e_2=d
\]</span></p>
<p>satisface (1) y (2) por reflexividad de la igualdad. Las fórmulas (3)–(5) se especializan así a los productos cruzados <span class="math inline">\(ad\)</span> y <span class="math inline">\(cb=bc\)</span>. Queda demostrado el corolario. <span class="math inline">\(\square\)</span></p>
<blockquote class="blockquote">
<p><strong>Lectura guiada.</strong> Normalizar no significa escoger una fracción irreducible. Sólo se necesita que ambos denominadores sean positivos. Después, su producto es positivo y la Proposición 27.28.1 entra siempre por su rama positiva. La prueba separa deliberadamente la <strong>existencia</strong> de representaciones positivas de la <strong>independencia del criterio respecto de cuál representación positiva se use</strong>.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Ejemplo ilustrativo, no premisa.</strong> En <span class="math inline">\(\mathbb Q\)</span>, comparar <span class="math inline">\(2/(-3)\)</span> con <span class="math inline">\(1/4\)</span> puede reemplazarse por comparar <span class="math inline">\((-2)/3\)</span> con <span class="math inline">\(1/4\)</span>. Como <span class="math inline">\(3,4&gt;0\)</span>, basta comparar <span class="math inline">\((-2)\cdot4\)</span> con <span class="math inline">\(1\cdot3\)</span>. El cambio de representación absorbe el signo del denominador antes de cruzar productos.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Error típico.</strong> La normalización no autoriza a comparar los numeradores solos: incluso con denominadores positivos, <span class="math inline">\(n_1/e_1&lt;n_2/e_2\)</span> depende de los productos <span class="math inline">\(n_1e_2\)</span> y <span class="math inline">\(n_2e_1\)</span>. Tampoco convierte la representación positiva en única; la Proposición 27.30.1 sigue permitiendo amplificaciones por cualquier factor positivo no nulo.</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="síntesis-deductiva-del-capítulo" class="level2">
<h2 class="anchored" data-anchor-id="síntesis-deductiva-del-capítulo">27.36. Síntesis deductiva del capítulo</h2>
<p>El problema planteado en §27.0 era introducir la inversión y la división en un cuerpo totalmente ordenado <strong>sin perder el control del signo, del dominio de definición ni del sentido de las desigualdades</strong>. La cadena cerrada del capítulo puede resumirse así:</p>
<pre class="text"><code>cuerpo + anillo totalmente ordenado
        │
        ├── cuerpo ordenado (§27.1)
        │   ├── signo del inverso: conserva el signo (§§27.4–27.6)
        │   └── inversión: antítona dentro de cada región de signo (§§27.8–27.10)
        │
        ├── producto por inversos (§§27.12–27.16)
        │   ├── nulidad exacta y regla de signos
        │   ├── orden estricto: conserva o invierte según el signo
        │   └── orden no estricto: mismas equivalencias
        │
        └── división interna del cuerpo (§§27.18–27.34)
            ├── dominio F × F^× y cociente a/b = ab⁻¹
            ├── identidades, nulidad y solución única de xb = a
            ├── signos y comparación con denominador fijo
            ├── suma, producto, opuestos y cocientes sucesivos
            ├── productos cruzados con signo controlado
            ├── amplificación por factores no nulos
            ├── normalización existencial a denominador positivo
            └── comparación uniforme tras normalización positiva</code></pre>
<p>La separación entre <strong>inversión</strong> y <strong>división</strong> es esencial. Antes de §27.18, <span class="math inline">\(b^{-1}\)</span> es el inverso multiplicativo de un elemento no nulo; desde §27.18, <span class="math inline">\(a/b\)</span> es una abreviatura tipada de <span class="math inline">\(ab^{-1}\)</span> dentro del mismo cuerpo <span class="math inline">\(F\)</span>. Esta barra no identifica el elemento de <span class="math inline">\(F\)</span> con las clases fraccionarias construidas en el capítulo 24.</p>
<p>El control del signo también se mantiene separado del control de nulidad. La positividad o negatividad de un factor determina el sentido de una desigualdad; la inexistencia de productos nulos en un cuerpo, heredada de su condición de dominio íntegro, impide que una desigualdad estricta colapse a igualdad. En los resultados de cocientes se verifican los denominadores no nulos <strong>antes</strong> de formar cada expresión.</p>
<p>La normalización final no construye una forma canónica. Todo cociente admite una representación con denominador positivo, pero esa representación puede amplificarse por factores positivos no nulos. Lo que sí queda demostrado es que <strong>cualquier</strong> par de representaciones con denominadores positivos conduce al mismo criterio de comparación por productos cruzados.</p>
<p>Tampoco se ha demostrado una antitonicidad global de <span class="math inline">\(x\mapsto x^{-1}\)</span> sobre <span class="math inline">\(F\setminus\{0\}\)</span>: el resultado es válido separadamente entre positivos y entre negativos y falla al cruzar cero. Del mismo modo, la totalidad del orden se emplea como propiedad lógica de comparabilidad, no como algoritmo de decisión.</p>
<p>Finalmente, el capítulo no usa completitud, supremos, topología ni propiedad arquimediana. Esas nociones quedan fuera de este capítulo. No se utiliza el axioma de elección. La única dependencia clásica relevante en §27.28 es la ya incorporada en la Proposición 26.34.1 para obtener cancelación desde la condición (NZ).</p>
<hr>
<p><a href="../../libros/capitulos/tratado-de-algebra-capitulo-26-anillos-ordenados.html">← <strong>Capítulo 26 — Anillos ordenados</strong></a> · <a href="../../libros/otros/tratado-de-algebra.html"><strong>Tratado moderno de Álgebra</strong></a> · <a href="../../libros/capitulos/tratado-de-algebra-capitulo-28-propiedades-arquimedianas.html"><strong>Capítulo 28 — Propiedades arquimedianas</strong> →</a></p>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reutilización</h2><div class="quarto-appendix-contents"><div>GFDL-1.3-or-later</div></div></section></div></main> <!-- /main -->
<style>
/* Estilo acotado al artículo con el laboratorio MA-APP-0003. */
body:has(iframe[src$="MA-APP-0003-supremo-infimo.html"]) span.math.display {
  display: block;
  max-width: 100%;
  overflow-x: auto;
  overflow-y: hidden;
  scrollbar-width: thin;
  -webkit-overflow-scrolling: touch;
}
body:has(iframe[src$="MA-APP-0003-supremo-infimo.html"]) iframe[src$="MA-APP-0003-supremo-infimo.html"] {
  display: block;
  box-sizing: border-box;
  max-width: 100%;
}
</style>
<script>
/* Integración del laboratorio, cargado desde el mismo origen que el artículo. */
(() => {
  const attach = () => {
    const frame = document.querySelector('iframe[src$="MA-APP-0003-supremo-infimo.html"]');
    if (!frame) return;
    let observer;
    const resize = () => {
      try {
        const doc = frame.contentDocument;
        const main = doc && doc.querySelector('main');
        if (!main) return;
        const margin = parseFloat(doc.defaultView.getComputedStyle(main).marginBottom) || 0;
        const height = Math.ceil(main.getBoundingClientRect().bottom + margin + 4);
        if (height > 0 && Math.abs(frame.getBoundingClientRect().height - height) > 2) {
          frame.style.height = height + 'px';
        }
      } catch (_) {
        /* Si cambia el origen, el iframe conserva su scroll y su enlace externo. */
      }
    };
    const observe = () => {
      resize();
      if (observer) observer.disconnect();
      try {
        const main = frame.contentDocument && frame.contentDocument.querySelector('main');
        if (main && 'ResizeObserver' in window) {
          observer = new ResizeObserver(resize);
          observer.observe(main);
        }
      } catch (_) { /* Mantener el laboratorio funcional aun sin acceso al iframe. */ }
    };
    frame.addEventListener('load', observe);
    observe();
    window.addEventListener('resize', resize, { passive: true });
  };
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', attach, { once: true });
  } else attach();
})();
</script>
<script>
(() => {
  'use strict';

  const attach = () => {
    const main = document.querySelector('main.content');
    if (!main || main.querySelector(':scope > .ma-reader-tools')) return;

    const rootPx = parseFloat(getComputedStyle(document.documentElement).fontSize) || 16;
    const step = 0.08 * rootPx;
    const min = 0.90 * rootPx;
    const max = 1.50 * rootPx;
    let size = parseFloat(getComputedStyle(main).fontSize) || (1.06 * rootPx);

    const bar = document.createElement('div');
    bar.className = 'ma-reader-tools';
    bar.setAttribute('role', 'group');
    bar.setAttribute('aria-label', 'Tamaño del texto');

    const label = document.createElement('span');
    label.textContent = 'Lectura';
    bar.append(label);

    const apply = next => {
      size = Math.max(min, Math.min(max, next));
      main.style.setProperty('--ma-reader-size', size + 'px');
    };

    const button = (text, name, handler) => {
      const el = document.createElement('button');
      el.type = 'button';
      el.textContent = text;
      el.setAttribute('aria-label', name);
      el.addEventListener('click', handler);
      bar.append(el);
    };

    button('A−', 'Reducir tamaño de letra', () => apply(size - step));
    button('A+', 'Aumentar tamaño de letra', () => apply(size + step));
    button('Restablecer', 'Restablecer tamaño de letra', () => {
      main.style.removeProperty('--ma-reader-size');
      size = parseFloat(getComputedStyle(main).fontSize) || (1.06 * rootPx);
    });

    const title = main.querySelector('#title-block-header');
    if (title) title.after(bar);
    else main.prepend(bar);
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', attach, { once: true });
  } else {
    attach();
  }
})();
</script>
<script>
(() => {
  'use strict';

  const CATALOGS = [
    {
      url: new URL('/teoria/resultados/index.html', window.location.origin),
      defaultKind: 'result'
    },
    {
      url: new URL('/teoria/metodos/index.html', window.location.origin),
      defaultKind: 'method'
    }
  ];
  const PREVIEW_HASH = /^#(?:res|met|def)-/i;
  const cache = new Map();
  let catalog = new Map();
  let activeLink = null;
  let requestToken = 0;

  const panel = document.createElement('aside');
  panel.className = 'ma-result-preview';
  panel.id = 'ma-result-preview';
  panel.setAttribute('role', 'tooltip');
  panel.hidden = true;
  panel.innerHTML = [
    '<div class="ma-result-preview-kicker"></div>',
    '<div class="ma-result-preview-title"></div>',
    '<div class="ma-result-preview-summary"></div>'
  ].join('');
  document.body.append(panel);

  const kickerEl = panel.querySelector('.ma-result-preview-kicker');
  const titleEl = panel.querySelector('.ma-result-preview-title');
  const summaryEl = panel.querySelector('.ma-result-preview-summary');

  const normalizePath = pathname => pathname
    .replace(/\.(?:md|qmd)$/i, '.html')
    .replace(/\/index\.html$/i, '/');

  const keyFor = (href, base = document.baseURI) => {
    try {
      const url = new URL(href, base);
      if (url.origin !== window.location.origin) return null;
      return normalizePath(url.pathname) + url.hash;
    } catch (_) {
      return null;
    }
  };

  const kindForHash = (hash, fallback = 'result') => {
    if (/^#res-/i.test(hash)) return 'result';
    if (/^#met-/i.test(hash)) return 'method';
    if (/^#def-/i.test(hash)) return 'definition';
    return fallback;
  };

  const labelForKind = kind => ({
    result: 'Resultado',
    method: 'Método',
    definition: 'Definición'
  }[kind] || 'Referencia');

  const cleanText = text => (text || '')
    .replace(/\(\s*MA-[^)]+\)/g, '')
    .replace(/^\s*[—–-]\s*/, '')
    .replace(/\s+/g, ' ')
    .trim();

  const truncate = (text, max = 430) => {
    const clean = cleanText(text);
    if (clean.length <= max) return clean;
    const cut = clean.slice(0, max);
    const lastSpace = cut.lastIndexOf(' ');
    return cut.slice(0, lastSpace > 300 ? lastSpace : max).trimEnd() + '…';
  };

  const readCatalog = async ({ url: catalogUrl, defaultKind }) => {
    try {
      const response = await fetch(catalogUrl, { credentials: 'same-origin' });
      if (!response.ok) return [];
      const html = await response.text();
      const doc = new DOMParser().parseFromString(html, 'text/html');
      const entries = [];

      doc.querySelectorAll('main.content li').forEach(li => {
        const link = li.querySelector('a[href]');
        if (!link) return;
        const key = keyFor(link.getAttribute('href'), catalogUrl);
        if (!key) return;

        const url = new URL(link.getAttribute('href'), catalogUrl);
        const clone = li.cloneNode(true);
        clone.querySelectorAll('a, code').forEach(el => el.remove());
        const summary = cleanText(clone.textContent);

        entries.push([key, {
          title: cleanText(link.textContent),
          summary,
          kind: kindForHash(url.hash, defaultKind)
        }]);
      });

      return entries;
    } catch (_) {
      return [];
    }
  };

  const loadCatalog = async () => {
    const groups = await Promise.all(CATALOGS.map(readCatalog));
    const next = new Map();

    groups.flat().forEach(([key, value]) => {
      const existing = next.get(key);
      if (!existing || (!existing.summary && value.summary)) next.set(key, value);
    });

    return next;
  };

  const fallbackFromTarget = async url => {
    const cacheKey = normalizePath(url.pathname) + url.hash;
    if (cache.has(cacheKey)) return cache.get(cacheKey);

    const promise = (async () => {
      try {
        let doc;
        if (normalizePath(url.pathname) === normalizePath(window.location.pathname)) {
          doc = document;
        } else {
          const response = await fetch(url.pathname, { credentials: 'same-origin' });
          if (!response.ok) return null;
          doc = new DOMParser().parseFromString(await response.text(), 'text/html');
        }

        const id = decodeURIComponent(url.hash.slice(1));
        const target = doc.getElementById(id);
        if (!target) return null;

        let title = '';
        let text = '';

        if (/^H[1-6]$/.test(target.tagName)) {
          title = cleanText(target.textContent);
          const level = Number(target.tagName.slice(1));
          const parts = [];
          let node = target.nextElementSibling;
          while (node && parts.length < 5) {
            if (/^H[1-6]$/.test(node.tagName) && Number(node.tagName.slice(1)) <= level) break;
            const value = cleanText(node.textContent);
            if (value) parts.push(value);
            node = node.nextElementSibling;
          }
          text = parts.join(' ');
        } else {
          const heading = target.querySelector('h1,h2,h3,h4,h5,h6');
          const blockLabel = heading
            ? null
            : target.querySelector(':scope > p:first-child > strong');
          title = heading
            ? cleanText(heading.textContent)
            : blockLabel
              ? cleanText(blockLabel.textContent)
              : '';

          const clone = target.cloneNode(true);
          clone.querySelectorAll('script, style, button, nav').forEach(el => el.remove());

          if (heading) {
            const clonedHeading = clone.querySelector('h1,h2,h3,h4,h5,h6');
            if (clonedHeading) clonedHeading.remove();
          } else if (blockLabel) {
            const clonedLabel = clone.querySelector(':scope > p:first-child > strong');
            const labelParagraph = clonedLabel?.parentElement;
            if (labelParagraph?.parentElement === clone) labelParagraph.remove();
          }

          text = cleanText(clone.textContent);
        }

        return {
          title: title || labelForKind(kindForHash(url.hash)),
          summary: truncate(text),
          kind: kindForHash(url.hash)
        };
      } catch (_) {
        return null;
      }
    })();

    cache.set(cacheKey, promise);
    return promise;
  };

  const position = link => {
    if (panel.hidden || !link) return;
    const margin = 12;
    const gap = 10;
    const rect = link.getBoundingClientRect();
    const box = panel.getBoundingClientRect();

    let left = rect.left + (rect.width / 2) - (box.width / 2);
    left = Math.max(margin, Math.min(left, window.innerWidth - box.width - margin));

    let top = rect.bottom + gap;
    if (top + box.height > window.innerHeight - margin) {
      const above = rect.top - box.height - gap;
      if (above >= margin) top = above;
    }

    panel.style.left = Math.round(left) + 'px';
    panel.style.top = Math.round(top) + 'px';
  };

  const hide = () => {
    requestToken += 1;
    if (activeLink) activeLink.removeAttribute('aria-describedby');
    activeLink = null;
    panel.hidden = true;
  };

  const show = async link => {
    const url = new URL(link.href, document.baseURI);
    const token = ++requestToken;
    const key = keyFor(url.href);
    let item = key ? catalog.get(key) : null;

    if ((!item || !item.summary) && PREVIEW_HASH.test(url.hash)) {
      item = await fallbackFromTarget(url);
    }

    if (token !== requestToken || !item || !item.summary) return;

    const kind = item.kind || kindForHash(url.hash);
    activeLink = link;
    panel.dataset.kind = kind;
    kickerEl.textContent = labelForKind(kind);
    titleEl.textContent = item.title || cleanText(link.textContent) || labelForKind(kind);
    summaryEl.textContent = truncate(item.summary);
    link.dataset.maPreviewKind = kind;
    link.setAttribute('aria-describedby', panel.id);
    panel.hidden = false;
    requestAnimationFrame(() => position(link));
  };

  const attachLink = link => {
    if (link.dataset.maResultPreview === '1') return;
    const url = new URL(link.href, document.baseURI);
    const key = keyFor(url.href);
    if (!key) return;

    const isCandidate = catalog.has(key) || PREVIEW_HASH.test(url.hash);
    if (!isCandidate) return;

    const kind = catalog.get(key)?.kind || kindForHash(url.hash);
    link.dataset.maResultPreview = '1';
    link.dataset.maPreviewKind = kind;
    link.classList.add('ma-result-link');

    link.addEventListener('mouseenter', () => show(link));
    link.addEventListener('mouseleave', () => {
      if (document.activeElement !== link) hide();
    });
    link.addEventListener('focus', () => show(link));
    link.addEventListener('blur', hide);
  };

  const attach = async () => {
    catalog = await loadCatalog();
    document.querySelectorAll('main.content a[href]').forEach(attachLink);

    window.addEventListener('scroll', () => position(activeLink), { passive: true });
    window.addEventListener('resize', () => position(activeLink), { passive: true });
    document.addEventListener('keydown', event => {
      if (event.key === 'Escape') hide();
    });
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', attach, { once: true });
  } else {
    attach();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/matematicaabierta\.cl\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>