(()=>{'use strict';
const $=id=>document.getElementById(id);const fields=['a1','a2','b1','b2'];const s={a1:3,a2:1,b1:1,b2:3,x:0,tab:'sumas'};
const f=n=>{if(!Number.isFinite(n))return '—';if(Math.abs(n)<1e-11)n=0;return Number(n.toFixed(4)).toLocaleString('es-CL',{maximumFractionDigits:4});};
const norm=(x,y)=>Math.hypot(x,y);const nearly=(x,y=0)=>Math.abs(x-y)<=1e-9*Math.max(1,Math.abs(x),Math.abs(y));
const vals=()=>{let {a1,a2,b1,b2}=s;let A=a1*a1+a2*a2,B=b1*b1+b2*b2,C=a1*b1+a2*b2,det=a1*b2-a2*b1,D=det*det;return {A,B,C,det,D,L:C*C,R:A*B,an:Math.sqrt(A),bn:Math.sqrt(B)};};
function setTab(name){s.tab=name;['sumas','labbe','geo'].forEach(n=>{let selected=n===name;$('view-'+n).hidden=!selected;$('tab-'+n).setAttribute('aria-selected',String(selected));$('tab-'+n).tabIndex=selected?0:-1;});update();}
['sumas','labbe','geo'].forEach(n=>{$('tab-'+n).addEventListener('click',()=>setTab(n));$('tab-'+n).addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let names=['sumas','labbe','geo'],idx=names.indexOf(n);let next=e.key==='Home'?0:e.key==='End'?2:(idx+(e.key==='ArrowRight'?1:2))%3;setTab(names[next]);$('tab-'+names[next]).focus();});});
function updateState(){let {A,B,C,D,L,R,det,an,bn}=vals();$('lhs').textContent=f(L);$('rhs').textContent=f(R);$('gap').textContent=f(D);$('sums-equation').textContent='('+f(s.a1)+' × '+f(s.b1)+' + '+f(s.a2)+' × '+f(s.b2)+')² ≤ ('+f(A)+')('+f(B)+')';$('identity').textContent=f(R)+' − '+f(L)+' = ('+f(s.a1)+' × '+f(s.b2)+' − '+f(s.a2)+' × '+f(s.b1)+')² = '+f(D)+' ≥ 0';$('bounds-comparison').textContent='Comparar cotas (Steele): |Σaᵢbᵢ| = '+f(Math.abs(C))+' ≤ cota multiplicativa '+f(Math.sqrt(R))+' ≤ cota aditiva '+f((A+B)/2)+'. La segunda desigualdad mide el efecto de escalas distintas; no es el defecto D.';let isZero=A===0||B===0,equal=D===0,orthogonal=C===0&&!isZero;let label=isZero?'Igualdad por vector nulo: no hay que dividir por su longitud.':equal?'Igualdad: las dos listas son linealmente dependientes.':orthogonal?'Desigualdad estricta: suma de productos cero, pero ambas listas son no nulas.':'Desigualdad estricta: el defecto cuadrático es positivo.';$('state-sums').textContent=label;$('state-geo').textContent=label;$('state-sums').classList.toggle('warn',!equal);$('state-geo').classList.toggle('warn',!equal);$('absdot').textContent=f(Math.abs(C));$('bound').textContent=f(an*bn);$('det-square').textContent=f(D);$('geometry-equation').textContent='|⟨a,b⟩| = '+f(Math.abs(C))+' ≤ '+f(an)+' × '+f(bn)+' = '+f(an*bn)+'.  Defecto cuadrático = '+f(D)+'.';$('graph-alt').textContent='Vector a = ('+f(s.a1)+', '+f(s.a2)+'), vector b = ('+f(s.b1)+', '+f(s.b2)+'). '+(isZero?'Hay un vector nulo.':orthogonal?'Son perpendiculares.':equal?'Son proporcionales.':'No son proporcionales.')+' Determinante = '+f(det)+'.';$('plane-desc').textContent=$('graph-alt').textContent;}
function plotGeom(){let {A,B,C}=vals(),z=(x,y)=>[250+15*x,190-15*y],origin=z(0,0),u=z(s.a1,s.a2),v=z(s.b1,s.b2),uv=z(s.a1+s.b1,s.a2+s.b2);$('area').setAttribute('points',[origin,u,uv,v].map(p=>p.join(',')).join(' '));for(let [id,p] of [['arrow-a',u],['arrow-b',v]]){$(id).setAttribute('x2',p[0]);$(id).setAttribute('y2',p[1]);}for(let [id,p] of [['label-a',u],['label-b',v]]){$(id).setAttribute('x',Math.min(472,p[0]+8));$(id).setAttribute('y',Math.max(20,p[1]-8));}if(B!==0){let p=z(C/B*s.b1,C/B*s.b2);$('projline').setAttribute('x1',u[0]);$('projline').setAttribute('y1',u[1]);$('projline').setAttribute('x2',p[0]);$('projline').setAttribute('y2',p[1]);$('projline').style.display='';}else{$('projline').style.display='none';}}
function refreshRange(){let {A,C}=vals(),xopt=A!==0?-C/A:0,limit=Math.min(100000,Math.max(15,Math.ceil(Math.max(Math.abs(xopt),Math.abs(s.x))+3)));$('xrange').min=-limit;$('xrange').max=limit;}
function updateQ(){let {A,B,C,D}=vals(),xopt=A!==0?-C/A:null,q=x=>A*x*x+2*C*x+B,qv=q(s.x),qmin=xopt===null?B:D/A;$('qformula').textContent='q(x) = '+f(A)+' x² '+(C<0?'− ':'+ ')+f(Math.abs(2*C))+' x + '+f(B)+' = Σ(aᵢx + bᵢ)² ≥ 0';$('qvalue').textContent=f(qv);$('xopt').textContent=xopt===null?'No único':f(xopt);$('qmin').textContent=f(qmin);$('state-labbe').textContent=xopt===null?'La lista a es nula: q(x) es constante; aquí no está permitido dividir por Σaᵢ².':nearly(s.x,xopt)?'Has elegido el parámetro que minimiza q(x). Su mínimo es '+f(qmin)+'.':'Prueba a encontrar el mínimo. El parámetro óptimo depende de las listas y puede ser negativo.';$('state-labbe').classList.toggle('warn',xopt!==null&&!nearly(s.x,xopt));let low=-Math.max(3,Math.abs(xopt||0)+2,Math.abs(s.x)+1),high=-low;let xs=[],maxq=0;for(let i=0;i<=100;i++){let xx=low+(high-low)*i/100,xq=q(xx);xs.push([xx,xq]);maxq=Math.max(maxq,xq);}maxq=Math.max(1,maxq);let point=(x,y)=>[20+(x-low)/(high-low)*460,170-y/maxq*145];$('qcurve').setAttribute('d',xs.map(([x,y],i)=>{let p=point(x,y);return (i?' L':'M')+p[0].toFixed(2)+' '+p[1].toFixed(2);}).join(''));let p=point(s.x,qv);$('qpoint').setAttribute('cx',p[0]);$('qpoint').setAttribute('cy',p[1]);$('qminimum').style.display=xopt===null?'none':'';if(xopt!==null){let mp=point(xopt,qmin);$('qminimum').setAttribute('cx',mp[0]);$('qminimum').setAttribute('cy',mp[1]);}$('q-chart-note').textContent='Curva violeta: q(x); punto dorado: x elegido; punto verde: mínimo'+(xopt===null?' (no único).':'.')+' La gráfica ajusta su escala y no constituye una demostración.';}
function update(){refreshRange();updateState();updateQ();plotGeom();}
function inputField(k,type){let e=$(k+(type==='range'?'range':'num'));e.addEventListener(type==='range'?'input':'change',()=>{let v=Number(e.value);if(!Number.isFinite(v)){e.value=s[k];return;}s[k]=Math.round(Math.min(6,Math.max(-6,v))*2)/2;$(k+'range').value=s[k];$(k+'num').value=s[k];update();});}
fields.forEach(k=>{inputField(k,'range');inputField(k,'num');});
const presets={general:[3,1,1,3],scale:[6,0,1,0],equal:[1,2,2,4],opposite:[1,2,-2,-4],orthogonal:[1,0,0,1],zero:[0,0,3,-1]};function preset(name){let v=presets[name];fields.forEach((k,i)=>{s[k]=v[i];$(k+'range').value=v[i];$(k+'num').value=v[i];});s.x=0;$('xnum').value=0;$('xrange').value=0;update();}document.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>preset(btn.dataset.preset)));$('reset').addEventListener('click',()=>{preset('general');setTab('sumas');});document.querySelectorAll('[data-next]').forEach(btn=>btn.addEventListener('click',()=>{$('tab-'+btn.dataset.next).click();$('tab-'+btn.dataset.next).focus();}));
function chooseX(v){if(!Number.isFinite(v))return;s.x=v;$('xnum').value=v;let range=$('xrange');range.min=Math.min(Number(range.min),Math.floor(v-2));range.max=Math.max(Number(range.max),Math.ceil(v+2));range.value=v;updateQ();}$('xrange').addEventListener('input',()=>chooseX(Number($('xrange').value)));$('xnum').addEventListener('change',()=>{let v=Number($('xnum').value);if($('xnum').value.trim()===''||!Number.isFinite(v)){$('xnum').value=s.x;return;}chooseX(Math.max(-100000,Math.min(100000,v)));});$('set-optimal').addEventListener('click',()=>{let {A,C}=vals();if(A===0){chooseX(0);return;}chooseX(-C/A);$('xnum').focus();});$('copy').addEventListener('click',async()=>{let {A,B,C,D,L,R}=vals(),text='a=('+s.a1+','+s.a2+'), b=('+s.b1+','+s.b2+'); (Σaᵢbᵢ)²='+L+', (Σaᵢ²)(Σbᵢ²)='+R+', D='+D+'.';try{await navigator.clipboard.writeText(text);$('copy').textContent='Datos copiados';}catch(e){$('copy').textContent='Copia no disponible';}setTimeout(()=>{$('copy').textContent='Copiar datos del ejemplo';},2300);});
const grid=$('planegrid');for(let i=-6;i<=6;i++){for(let d of ['x','y']){let l=document.createElementNS('http://www.w3.org/2000/svg','line');let x=250+i*15,y=190-i*15;[['x1',d==='x'?x:20],['y1',d==='x'?20:y],['x2',d==='x'?x:480],['y2',d==='x'?360:y]].forEach(([k,v])=>l.setAttribute(k,v));l.setAttribute('class','gridline');grid.append(l);}}update();
if(window.parent!==window && typeof ResizeObserver!=='undefined'){
 const sendHeight=()=>window.parent.postMessage({type:'ma-cs-resize',height:Math.ceil(document.body.scrollHeight)},window.location.origin==='null'?'*':window.location.origin);
 new ResizeObserver(sendHeight).observe(document.body);
 window.addEventListener('load',sendHeight);
 sendHeight();
}
})();
