import MatematicaAbierta.Continuo.DivisionInternaRCA
import MatematicaAbierta.Continuo.DivisionBetaRCA
import MatematicaAbierta.Continuo.AritmeticaModularInternaRCA
import MatematicaAbierta.Continuo.ContratoExtensionBetaRCA
import MatematicaAbierta.Continuo.CalculoOrdenRCA
import MatematicaAbierta.Continuo.LecturasBetaRCA
import MatematicaAbierta.Continuo.EmparejamientoInternoRCA
import MatematicaAbierta.Continuo.SelectoresInternosRCA
import MatematicaAbierta.Continuo.PropiedadesTrazaRCA
import MatematicaAbierta.Continuo.ExtensionGraficaRCA
import MatematicaAbierta.Continuo.TotalidadTrazaRCA
import MatematicaAbierta.Continuo.CalculoRCA
import MatematicaAbierta.Continuo.TrazasInduccionRCA
import MatematicaAbierta.Continuo.ConstruccionBaseTrazaRCA
import MatematicaAbierta.Continuo.PuenteCertificadoRCA
import MatematicaAbierta.PrimerosResultados
import MatematicaAbierta.DesigualdadTriangular
import MatematicaAbierta.ConsecuenciasCuerpo
import MatematicaAbierta.CauchySchwarz
import MatematicaAbierta.CauchySchwarzFinito
import MatematicaAbierta.TeoriaDeFunciones.Diagonalizacion
import MatematicaAbierta.TeoriaDeFunciones.Reindexacion
import MatematicaAbierta.TeoriaDeFunciones.Correspondencias
import MatematicaAbierta.TeoriaDeFunciones.GraficasEstructurales
import MatematicaAbierta.TeoriaDeFunciones.SemanticaEquivalencia
import MatematicaAbierta.TeoriaDeFunciones.NaturalidadSondas
import MatematicaAbierta.TeoriaDeFunciones.DensidadTerminal
import MatematicaAbierta.Continuo.CertificadosOrdenFinito
import MatematicaAbierta.Continuo.SumasRacionalesFinitas
import MatematicaAbierta.Continuo.SintaxisAritmetica
import MatematicaAbierta.Continuo.ReversionModular
import MatematicaAbierta.Continuo.BandasCodigo
import MatematicaAbierta.Continuo.CodificacionResiduo
import MatematicaAbierta.Continuo.PuenteComprension
import MatematicaAbierta.Continuo.ProgramaTransparente
import MatematicaAbierta.Continuo.SimulacionAcotada
import MatematicaAbierta.Continuo.PrimerExito
import MatematicaAbierta.Continuo.ComputabilidadAproximante
import MatematicaAbierta.Continuo.NombresRaiz
import MatematicaAbierta.Continuo.DecididoresCortes
import MatematicaAbierta.Continuo.TerminacionCortes
import MatematicaAbierta.Continuo.IndicesCortes
import MatematicaAbierta.Continuo.SemanticaComparadorCortes
import MatematicaAbierta.Continuo.DecididoresCortesEfectivos
import MatematicaAbierta.Continuo.SumaCortesReduccion
import MatematicaAbierta.Continuo.ContradiccionUniforme
import MatematicaAbierta.Continuo.NoPertenenciaUniforme
import MatematicaAbierta.Continuo.EtapasUniformes
import MatematicaAbierta.Continuo.CertificadosSumaEfectivos
import MatematicaAbierta.Continuo.SemanticaCertificadosSuma
import MatematicaAbierta.Continuo.PrimitividadCertificadosSuma
import MatematicaAbierta.Continuo.CompletitudCertificadosSuma
import MatematicaAbierta.Continuo.IndicesSumaIrracional
import MatematicaAbierta.MCL.U00.L01_Proposiciones
import MatematicaAbierta.MCL.U00.L02_Igualdad

/-!
# Matemática Abierta: biblioteca formal
Este módulo importa las demostraciones completas que deben comprobarse en CI.
Cada módulo nuevo debe incorporarse aquí para que `lake build` lo verifique.
-/
